version: '2'
services:
  mysql:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: rails_conceptware_sales_orosi_imple
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: rails_conceptware_sales_orosi_imple_development
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
