#組織データ管理(A) - 部門(AT010)
CREATE TABLE AT010(
     CDBUMON CHAR(5) NOT NULL COMMENT '部門C',
     TXBUMON CHAR(30) NOT NULL COMMENT '部門名',
     NRKANRISYA CHAR(5) NOT NULL COMMENT '管理者№',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
CONSTRAINT AT010_PK PRIMARY KEY (CDBUMON)
);

#組織データ管理(A) - 部門構成(AT011)
CREATE TABLE AT011(
     CDBUMON CHAR(5) NOT NULL COMMENT '部門C',
     DTHAKKOUNENGETSU CHAR(6) NOT NULL COMMENT '発効年月',
     CDJYOUIBUMON CHAR(5) NOT NULL COMMENT '上位部門C',
     DTSIKKOUNENGETSU CHAR(6) COMMENT '失効年月',
CONSTRAINT AT011_PK PRIMARY KEY (CDBUMON, DTHAKKOUNENGETSU),
CONSTRAINT AT011_FK1 FOREIGN KEY (CDJYOUIBUMON) REFERENCES AT010 (CDBUMON),
CONSTRAINT AT011_FK2 FOREIGN KEY (CDBUMON) REFERENCES AT010 (CDBUMON)
);

#組織データ管理(A) - 従業員(AT020)
CREATE TABLE AT020(
     NRJYUGYOIN CHAR(5) NOT NULL COMMENT '従業員№',
     TXKANA CHAR(30) NOT NULL COMMENT 'カナ名',
     TXKANJI CHAR(30) NOT NULL COMMENT '漢字名',
     KBKOYOU CHAR(2) NOT NULL COMMENT '雇用区分',
     DTNYUSYA DATE NOT NULL COMMENT '入社日',
     DTTAISYA DATE COMMENT '退社日',
CONSTRAINT AT020_PK PRIMARY KEY (NRJYUGYOIN)
);

#組織データ管理(A) - 従業員所属部門(AT021)
CREATE TABLE AT021(
     NRJYUGYOIN CHAR(5) NOT NULL COMMENT '従業員№',
     DTSYOZOKUNENGETSU CHAR(6) NOT NULL COMMENT '所属発効年月',
     CDBUMON CHAR(5) NOT NULL COMMENT '部門C',
     DTLASTNENGETSU CHAR(6) NOT NULL COMMENT '所属最終年月',
     KBPRESENT CHAR(1) NOT NULL COMMENT '現行メンバー区分',
CONSTRAINT AT021_PK PRIMARY KEY (NRJYUGYOIN, DTSYOZOKUNENGETSU),
CONSTRAINT AT021_FK1 FOREIGN KEY (NRJYUGYOIN) REFERENCES AT020 (NRJYUGYOIN),
CONSTRAINT AT021_FK2 FOREIGN KEY (CDBUMON) REFERENCES AT010 (CDBUMON)
);

#組織データ管理(A) - 取引先(AT030)
CREATE TABLE AT030(
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '取引先№',
     TXKANA CHAR(40) NOT NULL COMMENT 'カナ名',
     TXKANJI CHAR(40) NOT NULL COMMENT '漢字名',
     KBCOUNTRY CHAR(3) NOT NULL COMMENT '国コード',
     KBCURRENCY CHAR(3) NOT NULL COMMENT '取引通貨',
     NRYUBIN CHAR(8) NOT NULL COMMENT '郵便番号',
     TXJYUSYO1 CHAR(30) NOT NULL COMMENT '住所１',
     TXJYUSYO2 CHAR(30) COMMENT '住所２',
     NRDENWA CHAR(14) NOT NULL COMMENT '代表電話番号',
     NRFAX CHAR(14) NOT NULL COMMENT 'FAX番号',
     TXURL CHAR(40) COMMENT 'ＵＲＬ',
     FGKOKYAKU CHAR(1) NOT NULL COMMENT '顧客対象FLAG',
     FGSIIRESAKI CHAR(1) NOT NULL COMMENT '仕入先対象FLAG',
CONSTRAINT AT030_PK PRIMARY KEY (NRTORIHIKISAKI),
CONSTRAINT AT030_SK1 UNIQUE (TXKANJI)
);

#商品データ管理(B) - メーカー(BT010)
CREATE TABLE BT010(
     CDMAKER CHAR(5) NOT NULL COMMENT 'メーカー№',
     TXMAKER CHAR(40) NOT NULL COMMENT 'メーカー名',
     TXMAKERABR CHAR(10) NOT NULL COMMENT 'メーカー略称',
     KBCOUNTRY CHAR(3) NOT NULL COMMENT '国コード',
     NRYUBIN CHAR(8) NOT NULL COMMENT '郵便番号',
     TXJYUSYO CHAR(40) NOT NULL COMMENT '住所',
     NRDENWA CHAR(14) NOT NULL COMMENT '代表電話番号',
     NRFAX CHAR(14) NOT NULL COMMENT 'FAX番号',
     TXURL CHAR(40) COMMENT 'ＵＲＬ',
     TXEMAIL CHAR(40) COMMENT '担当者メアド',
CONSTRAINT BT010_PK PRIMARY KEY (CDMAKER)
);

#商品データ管理(B) - 商品(BT020)
CREATE TABLE BT020(
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     TXSYOHIN CHAR(30) NOT NULL COMMENT '商品名',
     TXHINBAN CHAR(20) NOT NULL COMMENT '品番',
     TXSIYOU CHAR(50) COMMENT '仕様',
     TXIMAGEFILENAME CHAR(30) NOT NULL COMMENT '外観',
     KBSYOHIN CHAR(5) NOT NULL COMMENT '商品群区分',
     CDMAKER CHAR(5) NOT NULL COMMENT 'メーカーＣ',
     PRHANBAI INTEGER COMMENT '標準売価',
     PRSIIRE INTEGER COMMENT '標準仕入価格',
     KBZAIKOUM CHAR(2) NOT NULL COMMENT '在庫単位区分',
     QTHANBAIUNIT INTEGER NOT NULL COMMENT '販売単位数',
     QTANZENZAIKO INTEGER COMMENT '安全在庫省略値',
     QTJYOUGENZAIKO INTEGER NOT NULL COMMENT '上限在庫省略値',
     FGLOTKANRI CHAR(1) NOT NULL COMMENT 'ロット管理対象',
     FGLISTSYOHIN CHAR(1) NOT NULL COMMENT '一覧表示対象',
     PRARARI INTEGER COMMENT '標準粗利',
CONSTRAINT BT020_PK PRIMARY KEY (NRSYOHIN),
CONSTRAINT BT020_SK1 UNIQUE (TXHINBAN),
CONSTRAINT BT020_FK1 FOREIGN KEY (CDMAKER) REFERENCES BT010 (CDMAKER)
);

#商品データ管理(B) - セット構成(BT021)
CREATE TABLE BT021(
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     NRCHILD CHAR(7) NOT NULL COMMENT '構成品内部商品№',
     RTKOUSEI INTEGER NOT NULL COMMENT '構成数',
     SQLIST SMALLINT COMMENT '構成一覧順',
CONSTRAINT BT021_PK PRIMARY KEY (NRSYOHIN, NRCHILD),
CONSTRAINT BT021_FK1 FOREIGN KEY (NRSYOHIN) REFERENCES BT020 (NRSYOHIN)
);

#商品データ管理(B) - 倉庫(BT030)
CREATE TABLE BT030(
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     TXSOUKO CHAR(20) NOT NULL COMMENT '倉庫名',
     TXSOUKOENG CHAR(30) COMMENT '倉庫名(英文)',
     NRYUBIN CHAR(8) NOT NULL COMMENT '郵便番号',
     TXJYUSYO CHAR(40) NOT NULL COMMENT '住所',
     TXJYUSYOENG CHAR(40) COMMENT '住所(英文)',
     NRDENWA CHAR(14) NOT NULL COMMENT '電話番号',
     NRFAX CHAR(14) NOT NULL COMMENT 'FAX番号',
CONSTRAINT BT030_PK PRIMARY KEY (NRSOUKO)
);

#商品データ管理(B) - 倉庫ロケ(BT031)
CREATE TABLE BT031(
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     NRLOCATION CHAR(5) NOT NULL COMMENT 'ロケ№',
     TXTEKIYO CHAR(20) NOT NULL COMMENT '摘要',
CONSTRAINT BT031_PK PRIMARY KEY (NRSOUKO, NRLOCATION),
CONSTRAINT BT031_FK1 FOREIGN KEY (NRSOUKO) REFERENCES BT030 (NRSOUKO)
);

#買掛残高データ管理(C) - 仕入先(CT010)
CREATE TABLE CT010(
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     TXTANTOUBUSYO CHAR(30) NOT NULL COMMENT '仕入先担当部署',
     TXTANTOUSYA CHAR(40) COMMENT '仕入先担当者名',
     TXTANTOUSYASYOKUI CHAR(10) COMMENT '仕入先担当者職位',
     TXTANTOUSYAEMAIL CHAR(40) COMMENT '仕入先担当者メアド',
     TXTANTOUSYADENWA CHAR(20) COMMENT '仕入先担当者電話番号',
     KBSIHARAIHOUHOU CHAR(2) NOT NULL COMMENT '支払方法区分',
     TXHURIKOMISAKI CHAR(50) COMMENT '振込銀行口座',
     VLNYUKINSAITO SMALLINT NOT NULL COMMENT '支払入金サイト',
     NRTANTOUJYUGYOIN CHAR(5) NOT NULL COMMENT '仕入担当者№',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     AMKISYUKAIKAKE DECIMAL(11,2) COMMENT '期首買掛残高',
     AMKEIJYOU DECIMAL(11,2) COMMENT '当期計上額',
     AMSIHARAI DECIMAL(11,2) COMMENT '当期支払額',
     AMGENKAIKAKE DECIMAL(11,2) COMMENT '現買掛残高',
CONSTRAINT CT010_PK PRIMARY KEY (NRTORIHIKISAKI),
CONSTRAINT CT010_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES AT030 (NRTORIHIKISAKI)
);

#買掛残高データ管理(C) - 仕入先別商品明細(CT011)
CREATE TABLE CT011(
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     DTHAKKOU DATE NOT NULL COMMENT '発効日',
     DTSIKKOU DATE NOT NULL COMMENT '失効日',
     KBSIIREUM CHAR(5) NOT NULL COMMENT '仕入単位',
     QTSIIRETANNI INTEGER NOT NULL COMMENT '仕入単位数量',
     VLKANZANKEISU INTEGER NOT NULL COMMENT '仕入単位換算係数',
     PRSIIRETANKA DECIMAL(11,2) NOT NULL COMMENT '契約仕入単価',
     VLLEADTIME SMALLINT COMMENT '標準発注リードタイム',
CONSTRAINT CT011_PK PRIMARY KEY (NRSYOHIN, NRTORIHIKISAKI, DTHAKKOU),
CONSTRAINT CT011_FK1 FOREIGN KEY (NRSYOHIN) REFERENCES BT020 (NRSYOHIN),
CONSTRAINT CT011_FK2 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES CT010 (NRTORIHIKISAKI)
);

#買掛残高データ管理(C) - 買掛増減履歴(CT100)
CREATE TABLE CT100(
     NRSIIRE CHAR(7) NOT NULL COMMENT '買掛増減№',
     KBAKADEN CHAR(2) NOT NULL COMMENT '赤黒',
     FGVALID CHAR(1) NOT NULL COMMENT '効区',
     KBSIIRE CHAR(2) NOT NULL COMMENT '仕入区分',
     DTSIIRE DATE NOT NULL COMMENT '仕入日',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     NRSYOHIN CHAR(7) COMMENT '仕入商品№',
     TXSYOHIN CHAR(30) COMMENT '商品名／摘要',
     PRSIIRE DECIMAL(10,2) COMMENT '仕入単価',
     KBCURRENCY CHAR(3) COMMENT '通貨',
     QTSIIRE INTEGER COMMENT '仕入数量',
     KBSIIREUM CHAR(5) COMMENT '仕入単位区分',
     AMSIIRE DECIMAL(11,2) NOT NULL COMMENT '税抜仕入額',
     AMTAX INTEGER COMMENT '消費税額',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     NRSIHARAIIRAI CHAR(7) COMMENT '支払依頼№',
     DTCREATE DATETIME NOT NULL COMMENT '記録日時',
     DTNEND SMALLINT NOT NULL COMMENT '取引年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '取引月序',
     AMSIIRENAIKA DECIMAL(11,2) NOT NULL COMMENT '税抜内貨仕入額',
CONSTRAINT CT100_PK PRIMARY KEY (NRSIIRE),
CONSTRAINT CT100_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES CT010 (NRTORIHIKISAKI),
CONSTRAINT CT100_FK2 FOREIGN KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI, NRSYOHIN) REFERENCES YT041 (DTNEND, DTMSEQ, NRTORIHIKISAKI, NRSYOHIN),
CONSTRAINT CT100_FK3 FOREIGN KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI) REFERENCES YT040 (DTNEND, DTMSEQ, NRTORIHIKISAKI)
);

#買掛残高データ管理(C) - 支払依頼(CT110)
CREATE TABLE CT110(
     NRSIHARAIIRAI CHAR(7) NOT NULL COMMENT '支払依頼№',
     DTSIHARAIIRAI DATE NOT NULL COMMENT '依頼日',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     TXSEIKYUNO CHAR(20) COMMENT '仕入先請求番号',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     FGSYOUNIN CHAR(1) NOT NULL COMMENT '支払承認フラグ',
     NRSIHARAI CHAR(7) COMMENT '支払指示№',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     KBSIHARAIHOUHOU CHAR(2) NOT NULL COMMENT '支払方法区分',
     AMSIHARAI DECIMAL(11,2) COMMENT '税抜支払依頼額',
     AMSIHARAINAIKA INTEGER COMMENT '税抜内貨支払額',
     AMTAX INTEGER COMMENT '消費税額',
CONSTRAINT CT110_PK PRIMARY KEY (NRSIHARAIIRAI),
CONSTRAINT CT110_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT CT110_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES CT010 (NRTORIHIKISAKI)
);

#買掛残高データ管理(C) - 支払指示(CT120)
CREATE TABLE CT120(
     NRSIHARAI CHAR(7) NOT NULL COMMENT '支払指示№',
     DTSIHARAI DATE NOT NULL COMMENT '支払日',
     KBSIHARAIHOUHOU CHAR(2) NOT NULL COMMENT '支払方法区分',
     KBCURRENCY CHAR(3) COMMENT '通貨',
     AMJITSUSIHARAI INTEGER COMMENT '内貨実際支払額',
     AMTESURYO INTEGER COMMENT '手数料',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     AMSIHARAI DECIMAL(11,2) COMMENT '税込支払指示額',
CONSTRAINT CT120_PK PRIMARY KEY (NRSIHARAI)
);

#売掛残高データ管理(D) - 顧客(DT010)
CREATE TABLE DT010(
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     CDKAKERITSURANK CHAR(2) NOT NULL COMMENT '掛率ランクＣ',
     TXTANTOUBUSYO CHAR(30) NOT NULL COMMENT '客先担当部署',
     TXTANTOUSYA CHAR(40) COMMENT '客先担当者名',
     TXTANTOUSYASYOKUI CHAR(10) COMMENT '客先担当者職位',
     TXTANTOUSYAEMAIL CHAR(40) COMMENT '客先担当者メアド',
     TXTANTOUSYADENWA CHAR(20) COMMENT '客先担当者電話番号',
     KBSEIKYUHOUSHIKI CHAR(2) NOT NULL COMMENT '請求方式区分',
     TXSIMEBI CHAR(10) NOT NULL COMMENT '締め日',
     CDNOUHINSYOYOSHIKI CHAR(4) COMMENT '納品書様式コード',
     KBNYUKINHOUHOU CHAR(2) NOT NULL COMMENT '標準入金方法区分',
     VLNYUKINSAITO SMALLINT NOT NULL COMMENT '売上入金サイト',
     AMYOSHIN INTEGER NOT NULL COMMENT '与信限度額',
     NRTANTOUJYUGYOIN CHAR(5) NOT NULL COMMENT '担当営業№',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     AMKISYUURIKAKE INTEGER COMMENT '期首売掛残高',
     AMKEIJYOU INTEGER COMMENT '当期計上額',
     AMKAISYU INTEGER COMMENT '当期回収額',
     AMGENURIKAKE INTEGER COMMENT '現売掛残高',
CONSTRAINT DT010_PK PRIMARY KEY (NRTORIHIKISAKI),
CONSTRAINT DT010_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES AT030 (NRTORIHIKISAKI),
CONSTRAINT DT010_FK2 FOREIGN KEY (NRTANTOUJYUGYOIN) REFERENCES AT020 (NRJYUGYOIN),
CONSTRAINT DT010_FK3 FOREIGN KEY (CDKAKERITSURANK) REFERENCES DT020 (CDKAKERITSURANK)
);

#売掛残高データ管理(D) - 出荷先(DT011)
CREATE TABLE DT011(
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     SQSYUKKASAKI SMALLINT NOT NULL COMMENT '出荷先行',
     TXKANJI CHAR(40) NOT NULL COMMENT '出荷先名',
     NRYUBIN CHAR(8) NOT NULL COMMENT '郵便番号',
     TXJYUSYO CHAR(40) NOT NULL COMMENT '住所',
     NRDENWA CHAR(14) NOT NULL COMMENT '代表電話番号',
     NRFAX CHAR(14) COMMENT 'FAX番号',
     VLUNSOULT SMALLINT NOT NULL COMMENT '運送リードタイム',
CONSTRAINT DT011_PK PRIMARY KEY (NRTORIHIKISAKI, SQSYUKKASAKI),
CONSTRAINT DT011_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES DT010 (NRTORIHIKISAKI)
);

#売掛残高データ管理(D) - 掛率ランク(DT020)
CREATE TABLE DT020(
     CDKAKERITSURANK CHAR(2) NOT NULL COMMENT '掛率ランクＣ',
     TXKAKERITSURANK CHAR(20) NOT NULL COMMENT 'ランク記述',
     VLKAKERITSU NUMERIC(3,2) NOT NULL COMMENT '掛率',
CONSTRAINT DT020_PK PRIMARY KEY (CDKAKERITSURANK)
);

#売掛残高データ管理(D) - 売掛増減履歴(DT100)
CREATE TABLE DT100(
     NRURIAGE CHAR(7) NOT NULL COMMENT '売掛増減№',
     KBAKADEN CHAR(2) NOT NULL COMMENT '赤黒',
     FGVALID CHAR(1) NOT NULL COMMENT '効区',
     KBURIAGE CHAR(2) NOT NULL COMMENT '売上区分',
     DTURIAGE DATE NOT NULL COMMENT '売上日',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     NRSYOHIN CHAR(7) COMMENT '売上商品№',
     TXSYOHIN CHAR(30) COMMENT '商品名／摘要',
     PRHANBAI INTEGER COMMENT '標準販売価格',
     PRURIAGE INTEGER COMMENT '売上単価',
     QTURIAGE INTEGER NOT NULL COMMENT '売上数量',
     KBURIAGEUM CHAR(5) NOT NULL COMMENT '売上単位区分',
     AMURIAGE INTEGER NOT NULL COMMENT '税抜売上額',
     AMTAX INTEGER COMMENT '消費税額',
     AMGENKA INTEGER COMMENT '売上原価',
     NRSEIKYU CHAR(7) COMMENT '請求№',
     NRJYUGYOIN CHAR(5) COMMENT '担当営業№',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     DTCREATE DATETIME NOT NULL COMMENT '記録日時',
     DTNEND SMALLINT NOT NULL COMMENT '取引年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '取引月序',
     AMNEBIKI INTEGER NOT NULL COMMENT '値引額',
     AMARARI INTEGER NOT NULL COMMENT '粗利額',
CONSTRAINT DT100_PK PRIMARY KEY (NRURIAGE),
CONSTRAINT DT100_FK1 FOREIGN KEY (NRSEIKYU) REFERENCES DT110 (NRSEIKYU),
CONSTRAINT DT100_FK2 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES DT010 (NRTORIHIKISAKI),
CONSTRAINT DT100_FK3 FOREIGN KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI) REFERENCES YT050 (DTNEND, DTMSEQ, NRTORIHIKISAKI),
CONSTRAINT DT100_FK4 FOREIGN KEY (DTNEND, DTMSEQ, NRJYUGYOIN) REFERENCES YT060 (DTNEND, DTMSEQ, NRTANTOUJYUGYOIN),
CONSTRAINT DT100_FK5 FOREIGN KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI, NRSYOHIN) REFERENCES YT051 (DTNEND, DTMSEQ, NRTORIHIKISAKI, NRSYOHIN)
);

#売掛残高データ管理(D) - 請求指示(DT110)
CREATE TABLE DT110(
     NRSEIKYU CHAR(7) NOT NULL COMMENT '請求№',
     DTSEIKYU DATE NOT NULL COMMENT '請求日',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     DTHAKKOU DATE COMMENT '発行日',
     DTNYUKIN DATE COMMENT '入金確認日',
     AMNYUKIN INTEGER COMMENT '前回以降入金額',
     AMSEIKYU INTEGER NOT NULL COMMENT '請求額',
     STSEIKYU CHAR(2) NOT NULL COMMENT '請求状況',
CONSTRAINT DT110_PK PRIMARY KEY (NRSEIKYU),
CONSTRAINT DT110_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES DT010 (NRTORIHIKISAKI)
);

#売掛残高データ管理(D) - 受領明細(DT120)
CREATE TABLE DT120(
     NRJYURYOU CHAR(7) NOT NULL COMMENT '受領№',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     DTJYURYOU DATE NOT NULL COMMENT '受領日',
     KBNYUKINHOUHOU CHAR(2) NOT NULL COMMENT '入金方法区分',
     AMJYURYOU INTEGER NOT NULL COMMENT '受領額',
     AMTESURYOU INTEGER COMMENT '手数料額',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
CONSTRAINT DT120_PK PRIMARY KEY (NRJYURYOU),
CONSTRAINT DT120_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT DT120_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES DT010 (NRTORIHIKISAKI)
);

#在庫残高データ管理(E) - 倉庫在庫(ET010)
CREATE TABLE ET010(
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     NRLOCATION CHAR(5) COMMENT '標準ロケ№',
     QTANZENZAIKO INTEGER COMMENT '安全在庫数',
     QTJYOUGENZAIKO INTEGER COMMENT '上限在庫数',
     QTKISYUZAIKO INTEGER COMMENT '期首在庫数',
     QTNYUKO INTEGER COMMENT '当期入庫数',
     QTSYUKKO INTEGER COMMENT '当期出庫数',
     AMKISYUZAIKO INTEGER COMMENT '期首在庫額',
     AMNYUKO INTEGER COMMENT '当期入庫額',
     AMSYUKKO INTEGER COMMENT '当期出庫額',
     QTGENZAIKO INTEGER COMMENT '現在庫数',
     AMGENZAIKO INTEGER COMMENT '現在庫額',
     PRIDOUHEIKIN INTEGER COMMENT '移動平均単価',
CONSTRAINT ET010_PK PRIMARY KEY (NRSYOHIN, NRSOUKO),
CONSTRAINT ET010_FK1 FOREIGN KEY (NRSYOHIN) REFERENCES BT020 (NRSYOHIN),
CONSTRAINT ET010_FK2 FOREIGN KEY (NRSOUKO) REFERENCES BT030 (NRSOUKO)
);

#在庫残高データ管理(E) - 受払履歴(ET100)
CREATE TABLE ET100(
     NRUKEBARAI CHAR(7) NOT NULL COMMENT '受払№',
     KBAKADEN CHAR(2) NOT NULL COMMENT '赤黒',
     FGVALID CHAR(1) NOT NULL COMMENT '効区',
     KBUKEBARAI CHAR(2) NOT NULL COMMENT '受払区分',
     DTUKEBARAI DATE NOT NULL COMMENT '受払日',
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     NRIDOUSOUKO CHAR(5) COMMENT '移動倉庫№',
     NRTORIHIKISAKI CHAR(8) COMMENT '取引先№',
     SQSYUKKASAKI SMALLINT COMMENT '出荷先行番',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     TXSYOHIN CHAR(30) COMMENT '商品名／摘要',
     TXLOTNUMBER CHAR(40) COMMENT 'ロット№',
     QTUKEBARAI INTEGER COMMENT '受払数量',
     AMUKEBARAI INTEGER COMMENT '受払金額',
     AMSAGAKU INTEGER COMMENT '取引差額',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     DTCREATE DATETIME NOT NULL COMMENT '記録日時',
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     SQMSEQ SMALLINT NOT NULL COMMENT '月度',
     TXAITESAKI CHAR(40) COMMENT '相手先名',
CONSTRAINT ET100_PK PRIMARY KEY (NRUKEBARAI),
CONSTRAINT ET100_FK1 FOREIGN KEY (DTNEND, SQMSEQ, NRSYOHIN, NRSOUKO) REFERENCES YT031 (DTNEND, DTMSEQ, NRSYOHIN, NRSOUKO),
CONSTRAINT ET100_FK2 FOREIGN KEY (NRSYOHIN, NRSOUKO) REFERENCES ET010 (NRSYOHIN, NRSOUKO)
);

#在庫残高データ管理(E) - 受払予定(ET200)
CREATE TABLE ET200(
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     KBYOTEI CHAR(2) NOT NULL COMMENT '受払予定区分',
     DTYOTEI DATE NOT NULL COMMENT '受払予定日',
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     NRIDOUSOUKO CHAR(5) COMMENT '移動倉庫№',
     NRTORIHIKISAKI CHAR(8) COMMENT '取引先№',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     QTYOTEI INTEGER COMMENT '受払予定数',
     NRSANSYOU CHAR(15) NOT NULL COMMENT '参照№',
     TXAITESAKI CHAR(40) COMMENT '相手先名',
CONSTRAINT ET200_PK PRIMARY KEY (NRTORIHIKIKANRI),
CONSTRAINT ET200_FK1 FOREIGN KEY (NRSYOHIN, NRSOUKO) REFERENCES ET010 (NRSYOHIN, NRSOUKO)
);

#発注・入荷データ管理(F) - 発注見出し(FT010)
CREATE TABLE FT010(
     NRHATTYU CHAR(7) NOT NULL COMMENT '発注№',
     DTHATTYU DATE NOT NULL COMMENT '発注日',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     NRJYUGYOIN CHAR(5) NOT NULL COMMENT '発注担当№',
     NRSOUKO CHAR(5) NOT NULL COMMENT '入荷予定倉庫№',
     FGKAKUNIN CHAR(1) NOT NULL COMMENT '納期確認',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     DTKIBOUNOUKI DATE NOT NULL COMMENT '希望納期初期値',
     DTHAKKO DATE COMMENT '発注書発行日',
     DTTORIKESHI DATE COMMENT '取消日',
     STHATTYU CHAR(2) NOT NULL COMMENT '発注状況',
CONSTRAINT FT010_PK PRIMARY KEY (NRHATTYU),
CONSTRAINT FT010_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES CT010 (NRTORIHIKISAKI)
);

#発注・入荷データ管理(F) - 発注明細(FT011)
CREATE TABLE FT011(
     NRHATTYU CHAR(7) NOT NULL COMMENT '発注№',
     SQHATTYU SMALLINT NOT NULL COMMENT '発注行',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '発注商品№',
     PRHATTYU DECIMAL(10,2) NOT NULL COMMENT '発注単価',
     QTHATTYU INTEGER NOT NULL COMMENT '発注数量',
     DTKIBOUNOUKI DATE NOT NULL COMMENT '希望納期',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     DTHAKKOU DATE NOT NULL COMMENT '発効日',
     QTHATTYUKANZAN INTEGER NOT NULL COMMENT '在庫換算数',
CONSTRAINT FT011_PK PRIMARY KEY (NRHATTYU, SQHATTYU),
CONSTRAINT FT011_FK1 FOREIGN KEY (NRHATTYU) REFERENCES FT010 (NRHATTYU),
CONSTRAINT FT011_FK2 FOREIGN KEY (NRSYOHIN, NRTORIHIKISAKI, DTHAKKOU) REFERENCES CT011 (NRSYOHIN, NRTORIHIKISAKI, DTHAKKOU)
);

#発注・入荷データ管理(F) - 入荷明細(FT012)
CREATE TABLE FT012(
     NRHATTYU CHAR(7) NOT NULL COMMENT '発注№',
     SQHATTYU SMALLINT NOT NULL COMMENT '発注行',
     SQNYUKA SMALLINT NOT NULL COMMENT '入荷行',
     DTYOTEINYUKA DATE NOT NULL COMMENT '予定入荷日',
     FGKAKUNIN CHAR(1) NOT NULL COMMENT '納期確認',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '入荷商品№',
     QTYOTEISIIRE INTEGER NOT NULL COMMENT '仕入予定数',
     QTJITSUSIIRE INTEGER COMMENT '実際仕入数',
     QTDEFECT INTEGER COMMENT '不合格数',
     PRSIIRE DECIMAL(10,2) NOT NULL COMMENT '仕入単価',
     TXLOTNUMBER CHAR(40) COMMENT 'ロット№',
     NRLOCATION CHAR(5) COMMENT '入庫ロケ№',
     NRNYUKA CHAR(7) COMMENT '入荷№',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     NRSOUKO CHAR(5) COMMENT '予定入荷倉庫№',
     DTNYUKA DATE COMMENT '実際入荷日',
     QTYOTEINYUKO INTEGER COMMENT '入庫予定数',
     QTJITSUNYUKO INTEGER COMMENT '実際入庫数',
     AMSIIREGAIKA DECIMAL(11,2) COMMENT '外貨仕入額',
     AMSIIRENAIKA INTEGER COMMENT '内貨仕入額',
     AMTAX INTEGER COMMENT '消費税額',
CONSTRAINT FT012_PK PRIMARY KEY (NRHATTYU, SQHATTYU, SQNYUKA),
CONSTRAINT FT012_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT FT012_FK1 FOREIGN KEY (NRHATTYU, SQHATTYU) REFERENCES FT011 (NRHATTYU, SQHATTYU),
CONSTRAINT FT012_FK2 FOREIGN KEY (NRTORIHIKIKANRI) REFERENCES ET200 (NRTORIHIKIKANRI)
);

#発注・入荷データ管理(F) - 入荷見出し(FT020)
CREATE TABLE FT020(
     NRNYUKA CHAR(7) NOT NULL COMMENT '入荷№',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     DTNYUKA DATE NOT NULL COMMENT '入荷日',
     DTSIIRE DATE NOT NULL COMMENT '仕入計上日',
     NRSOUKO CHAR(5) NOT NULL COMMENT '入荷倉庫№',
     STNYUKA CHAR(2) NOT NULL COMMENT '入荷状況',
CONSTRAINT FT020_PK PRIMARY KEY (NRNYUKA),
CONSTRAINT FT020_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES CT010 (NRTORIHIKISAKI)
);

#受注・出荷データ管理(G) - 受注見出し(GT010)
CREATE TABLE GT010(
     NRJYUTYU CHAR(7) NOT NULL COMMENT '受注№',
     DTJYUTYU DATE NOT NULL COMMENT '受注日',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     SQSYUKKASAKI SMALLINT NOT NULL COMMENT '出荷先行番',
     TXTYUBAN CHAR(15) COMMENT '顧客注文番号',
     NRSOUKO CHAR(5) NOT NULL COMMENT '出荷予定倉庫№',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     DTTORIKESHI DATE COMMENT '取消日',
     NRMITSUMORI CHAR(7) COMMENT '見積№',
     SQVERSION SMALLINT COMMENT '見積版№',
     STJYUTYU CHAR(2) NOT NULL COMMENT '受注状況',
CONSTRAINT GT010_PK PRIMARY KEY (NRJYUTYU),
CONSTRAINT GT010_FK1 FOREIGN KEY (NRTORIHIKISAKI, SQSYUKKASAKI) REFERENCES DT011 (NRTORIHIKISAKI, SQSYUKKASAKI)
);

#受注・出荷データ管理(G) - 受注明細(GT011)
CREATE TABLE GT011(
     NRJYUTYU CHAR(7) NOT NULL COMMENT '受注№',
     SQJYUTYU SMALLINT NOT NULL COMMENT '受注行',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '受注商品№',
     PRJYUTYU INTEGER NOT NULL COMMENT '受注単価',
     QTJYUTYU INTEGER NOT NULL COMMENT '受注数量',
     DTKIBOUNOUKI DATE NOT NULL COMMENT '希望納期',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     QTSYUKKAZUMI INTEGER COMMENT '出荷済数量',
     QTSYUKKAZAN INTEGER COMMENT '出荷残数量',
CONSTRAINT GT011_PK PRIMARY KEY (NRJYUTYU, SQJYUTYU),
CONSTRAINT GT011_FK1 FOREIGN KEY (NRJYUTYU) REFERENCES GT010 (NRJYUTYU),
CONSTRAINT GT011_FK2 FOREIGN KEY (NRSYOHIN) REFERENCES BT020 (NRSYOHIN)
);

#受注・出荷データ管理(G) - 出荷明細(GT012)
CREATE TABLE GT012(
     NRJYUTYU CHAR(7) NOT NULL COMMENT '受注№',
     SQJYUTYU SMALLINT NOT NULL COMMENT '受注行',
     SQSYUKKA SMALLINT NOT NULL COMMENT '出荷行',
     NRSOUKO CHAR(5) NOT NULL COMMENT '出荷倉庫№',
     DTYOTEISYUKKA DATE NOT NULL COMMENT '予定出荷日',
     QTYOTEISYUKKA INTEGER NOT NULL COMMENT '出荷指示数',
     PRSYUKKO INTEGER COMMENT '出庫単価',
     PRSYUKKA INTEGER NOT NULL COMMENT '販売価格',
     QTJITSUSYUKKA INTEGER COMMENT '出荷実績数',
     QTTORIKESHI INTEGER COMMENT '出荷取消数',
     TXLOTNUMBER CHAR(40) COMMENT 'ロット№',
     NRSYUKKA CHAR(7) COMMENT '出荷№',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     AMTAX INTEGER COMMENT '消費税額',
     TXBUNNOU CHAR(5) NOT NULL COMMENT '分納マーク',
CONSTRAINT GT012_PK PRIMARY KEY (NRJYUTYU, SQJYUTYU, SQSYUKKA),
CONSTRAINT GT012_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT GT012_FK1 FOREIGN KEY (NRJYUTYU, SQJYUTYU) REFERENCES GT011 (NRJYUTYU, SQJYUTYU),
CONSTRAINT GT012_FK2 FOREIGN KEY (NRTORIHIKIKANRI) REFERENCES ET200 (NRTORIHIKIKANRI)
);

#受注・出荷データ管理(G) - 出荷見出し(GT020)
CREATE TABLE GT020(
     NRSYUKKA CHAR(7) NOT NULL COMMENT '出荷№',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     SQSYUKKASAKI SMALLINT NOT NULL COMMENT '出荷先行番',
     NRSOUKO CHAR(5) NOT NULL COMMENT '出荷倉庫№',
     DTSYUKKA DATE NOT NULL COMMENT '出荷日',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRSEIKYU CHAR(7) COMMENT '都度請求№',
     TMHAKKOU DATETIME COMMENT '発行日時',
     TMKANRYO DATETIME COMMENT '完了日時',
     STSYUKKA CHAR(2) NOT NULL COMMENT '状況区分',
CONSTRAINT GT020_PK PRIMARY KEY (NRSYUKKA),
CONSTRAINT GT020_SK1 UNIQUE (NRSEIKYU),
CONSTRAINT GT020_FK1 FOREIGN KEY (NRTORIHIKISAKI, SQSYUKKASAKI) REFERENCES DT011 (NRTORIHIKISAKI, SQSYUKKASAKI)
);

#受注・出荷データ管理(G) - 見積見出し(GT030)
CREATE TABLE GT030(
     NRMITSUMORI CHAR(7) NOT NULL COMMENT '見積№',
     SQVERSION SMALLINT NOT NULL COMMENT '見積版№',
     DTMITSUMORI DATE NOT NULL COMMENT '見積日',
     NRTORIHIKISAKI CHAR(8) COMMENT '顧客№',
     SQSYUKKASAKI SMALLINT COMMENT '出荷先行番',
     TXKOKYAKUMEI CHAR(40) COMMENT '未登録顧客名',
     TXTYUBAN CHAR(15) COMMENT '顧客注文番号',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRJYUTYU CHAR(7) COMMENT '受注№',
CONSTRAINT GT030_PK PRIMARY KEY (NRMITSUMORI, SQVERSION)
);

#受注・出荷データ管理(G) - 見積明細(GT031)
CREATE TABLE GT031(
     NRMITSUMORI CHAR(7) NOT NULL COMMENT '見積№',
     SQVERSION SMALLINT NOT NULL COMMENT '見積版№',
     SQMITSUMORI SMALLINT NOT NULL COMMENT '見積行',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '見積商品№',
     PRJYUTYU INTEGER NOT NULL COMMENT '見積単価',
     QTJYUTYU INTEGER NOT NULL COMMENT '注文数量',
     DTKIBOUNOUKI DATE NOT NULL COMMENT '希望納期',
CONSTRAINT GT031_PK PRIMARY KEY (NRMITSUMORI, SQVERSION, SQMITSUMORI),
CONSTRAINT GT031_FK1 FOREIGN KEY (NRSYOHIN) REFERENCES BT020 (NRSYOHIN),
CONSTRAINT GT031_FK2 FOREIGN KEY (NRMITSUMORI, SQVERSION) REFERENCES GT030 (NRMITSUMORI, SQVERSION)
);

#一般仕入取引データ管理(H) - 仕入振替(HT010)
CREATE TABLE HT010(
     NRSIIREHURIKAE CHAR(7) NOT NULL COMMENT '仕入振替№',
     KBSIIREHURIKAE CHAR(2) NOT NULL COMMENT '振替区分',
     DTTORIHIKI DATE NOT NULL COMMENT '取引日',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     AMTORIHIKI INTEGER NOT NULL COMMENT '税抜取引額',
     TXTEKIYO CHAR(30) COMMENT '振替摘要',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     AMTAX INTEGER COMMENT '消費税額',
CONSTRAINT HT010_PK PRIMARY KEY (NRSIIREHURIKAE),
CONSTRAINT HT010_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT HT010_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES CT010 (NRTORIHIKISAKI)
);

#一般仕入取引データ管理(H) - 特殊仕入(HT020)
CREATE TABLE HT020(
     NRTOKUSYUSIIRE CHAR(7) NOT NULL COMMENT '特殊仕入№',
     KBTOKUSYUSIIRE CHAR(2) NOT NULL COMMENT '取引区分',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     DTTORIHIKI DATE NOT NULL COMMENT '取引日',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '商品№',
     NRSOUKO CHAR(5) NOT NULL COMMENT '取引倉庫№',
     NRLOCATION CHAR(5) NOT NULL COMMENT 'ロケ№',
     TXLOTNUMBER CHAR(40) COMMENT 'ロット№',
     PRTORIHIKI DECIMAL(10,2) NOT NULL COMMENT '取引単価',
     QTTORIHIKI INTEGER NOT NULL COMMENT '取引数量',
     KBTORIHIKIUM CHAR(5) NOT NULL COMMENT '取引単位区分',
     PRUKEBARAI INTEGER COMMENT '受払単価',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     QTTORIHIKI INTEGER NOT NULL COMMENT '在庫単位換算数',
     AMTORIHIKI DECIMAL(10,2) COMMENT '税抜取引額',
     AMTORIHIKINAIKA INTEGER COMMENT '内貨税抜取引額',
     AMTAX INTEGER COMMENT '消費税額',
     DTHAKKOU DATE NOT NULL COMMENT '発効日',
CONSTRAINT HT020_PK PRIMARY KEY (NRTOKUSYUSIIRE),
CONSTRAINT HT020_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT HT020_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES CT010 (NRTORIHIKISAKI)
);

#一般売上取引データ管理(J) - 売上振替(JT010)
CREATE TABLE JT010(
     NRURIAGEHURIKAE CHAR(7) NOT NULL COMMENT '売上振替№',
     KBURIAGEHURIKAE CHAR(2) NOT NULL COMMENT '振替区分',
     DTTORIHIKI DATE NOT NULL COMMENT '取引日',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     AMTORIHIKI DECIMAL(10,2) NOT NULL COMMENT '税抜取引額',
     TXTEKIYO CHAR(30) NOT NULL COMMENT '振替摘要',
     NRSEIKYU CHAR(7) NOT NULL COMMENT '都度請求№',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     AMTAX INTEGER NOT NULL COMMENT '消費税額',
CONSTRAINT JT010_PK PRIMARY KEY (NRURIAGEHURIKAE),
CONSTRAINT JT010_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT JT010_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES DT010 (NRTORIHIKISAKI)
);

#一般売上取引データ管理(J) - 特殊売上(JT020)
CREATE TABLE JT020(
     NRTOKUSYUURIAGE CHAR(7) NOT NULL COMMENT '特殊売上№',
     KBTOKUSYUURIAGE CHAR(2) NOT NULL COMMENT '取引区分',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     SQSYUKKASAKI SMALLINT NOT NULL COMMENT '出荷先行番',
     DTTORIHIKI DATE NOT NULL COMMENT '取引日',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '商品№',
     NRSOUKO CHAR(5) NOT NULL COMMENT '取引倉庫№',
     NRLOCATION CHAR(5) NOT NULL COMMENT '入庫ロケ№',
     PRTORIHIKI INTEGER NOT NULL COMMENT '取引単価',
     QTTORIHIKI INTEGER NOT NULL COMMENT '取引数量',
     PRUKEBARAI INTEGER COMMENT '受払単価',
     TXLOTNUMBER CHAR(40) COMMENT 'ロット№',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRSEIKYU CHAR(7) COMMENT '都度請求№',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     AMTORIHIKI INTEGER COMMENT '税抜取引額',
     AMTAX INTEGER COMMENT '消費税額',
CONSTRAINT JT020_PK PRIMARY KEY (NRTOKUSYUURIAGE),
CONSTRAINT JT020_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT JT020_FK1 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES DT010 (NRTORIHIKISAKI)
);

#一般在庫取引データ管理(K) - 棚卸指示(KT010)
CREATE TABLE KT010(
     NRTANAOROSHI CHAR(7) NOT NULL COMMENT '棚卸№',
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     NRLOCATION CHAR(5) COMMENT 'ロケ№',
     DTKIJYUN DATETIME COMMENT '調査基準日時',
     DTKOUSHIN DATETIME COMMENT '確定更新日時',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     STTANAOROSHI CHAR(2) NOT NULL COMMENT '処理状況',
CONSTRAINT KT010_PK PRIMARY KEY (NRTANAOROSHI),
CONSTRAINT KT010_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT KT010_FK1 FOREIGN KEY (NRSOUKO) REFERENCES BT030 (NRSOUKO)
);

#一般在庫取引データ管理(K) - 棚卸指示明細(KT011)
CREATE TABLE KT011(
     NRTANAOROSHI CHAR(7) NOT NULL COMMENT '棚卸№',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '商品№',
     NRLOCATION CHAR(5) NOT NULL COMMENT 'ロケ№',
     PRUKEBARAI INTEGER COMMENT '受払単価',
     QTTYOUBO INTEGER COMMENT '帳簿在庫数量',
     QTJITSUTANA INTEGER COMMENT '実棚数量',
     QTSASUU INTEGER COMMENT '実棚差数',
     AMSAGAKU INTEGER COMMENT '実棚差額',
CONSTRAINT KT011_PK PRIMARY KEY (NRTANAOROSHI, NRSYOHIN),
CONSTRAINT KT011_FK1 FOREIGN KEY (NRTANAOROSHI) REFERENCES KT010 (NRTANAOROSHI)
);

#一般在庫取引データ管理(K) - 在庫移動指示(KT020)
CREATE TABLE KT020(
     NRZAIKOIDOU CHAR(7) NOT NULL COMMENT '移動指示№',
     DTSHIJI DATE NOT NULL COMMENT '指示日',
     NRSOUKOFROM CHAR(5) NOT NULL COMMENT '元倉庫№',
     NRSOUKOTO CHAR(5) NOT NULL COMMENT '先倉庫№',
     DTKANRYOYOTEI DATE NOT NULL COMMENT '完了予定日',
     TMHAKKOU DATETIME COMMENT '発行日時',
     TMKANRYO DATETIME COMMENT '完了日時',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     STZAIKOIDOU CHAR(2) NOT NULL COMMENT '状況区分',
CONSTRAINT KT020_PK PRIMARY KEY (NRZAIKOIDOU),
CONSTRAINT KT020_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT KT020_FK1 FOREIGN KEY (NRSOUKOFROM) REFERENCES BT030 (NRSOUKO)
);

#一般在庫取引データ管理(K) - 在庫移動指示明細(KT021)
CREATE TABLE KT021(
     NRZAIKOIDOU CHAR(7) NOT NULL COMMENT '移動指示№',
     SQZAIKOIDOU SMALLINT NOT NULL COMMENT '指示行',
     NRLOCATIONTO CHAR(5) COMMENT '先ロケ№',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '商品№',
     QTIDOU INTEGER NOT NULL COMMENT '移動数量',
     PRIDOU INTEGER COMMENT '取引単価',
     NRTORIHIKIKANRIFROM CHAR(7) NOT NULL COMMENT '出庫管理№',
     NRTORIHIKIKANRITO CHAR(7) NOT NULL COMMENT '入庫管理№',
CONSTRAINT KT021_PK PRIMARY KEY (NRZAIKOIDOU, SQZAIKOIDOU),
CONSTRAINT KT021_SK1 UNIQUE (NRTORIHIKIKANRIFROM),
CONSTRAINT KT021_SK2 UNIQUE (NRTORIHIKIKANRITO),
CONSTRAINT KT021_FK1 FOREIGN KEY (NRZAIKOIDOU) REFERENCES KT020 (NRZAIKOIDOU),
CONSTRAINT KT021_FK2 FOREIGN KEY (NRTORIHIKIKANRITO) REFERENCES ET200 (NRTORIHIKIKANRI),
CONSTRAINT KT021_FK3 FOREIGN KEY (NRTORIHIKIKANRIFROM) REFERENCES ET200 (NRTORIHIKIKANRI)
);

#一般在庫取引データ管理(K) - 在庫振替(KT030)
CREATE TABLE KT030(
     NRZAIKOHURIKAE CHAR(7) NOT NULL COMMENT '在庫振替№',
     KBZAIKOHURIKAE CHAR(2) NOT NULL COMMENT '振替区分',
     DTHURIKAE DATE NOT NULL COMMENT '振替日',
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     NRLOCATION CHAR(5) NOT NULL COMMENT 'ロケ№',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     QTHURIKAE INTEGER COMMENT '振替数量',
     AMHURIKAE INTEGER COMMENT '振替金額',
     TXLOTNUMBER CHAR(40) COMMENT 'ロット№',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
CONSTRAINT KT030_PK PRIMARY KEY (NRZAIKOHURIKAE),
CONSTRAINT KT030_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT KT030_FK1 FOREIGN KEY (NRSYOHIN) REFERENCES BT020 (NRSYOHIN)
);

#セット指示データ管理(L) - セット指示(LT010)
CREATE TABLE LT010(
     NRSET CHAR(7) NOT NULL COMMENT 'セット指示№',
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     DTYOTEI DATE NOT NULL COMMENT '作業予定日',
     TMHAKKOU DATETIME COMMENT '発行日時',
     TMJISSEKI DATETIME COMMENT '実際完了日時',
     NRSYOHIN CHAR(7) NOT NULL COMMENT 'セット品内部商品№',
     QTSHIJI INTEGER NOT NULL COMMENT '予定セット数',
     QTJISSEKI INTEGER COMMENT '実績セット数',
     AMJISSEKI INTEGER COMMENT '実績取引額',
     NRLOCATION CHAR(5) COMMENT 'ロケ№',
     TXLOTNUMBER CHAR(40) COMMENT 'ロット№',
     TXTEKIYO VARCHAR(300) COMMENT '摘要',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     STSET CHAR(2) NOT NULL COMMENT '指示状況',
CONSTRAINT LT010_PK PRIMARY KEY (NRSET),
CONSTRAINT LT010_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT LT010_FK1 FOREIGN KEY (NRSYOHIN) REFERENCES BT020 (NRSYOHIN),
CONSTRAINT LT010_FK2 FOREIGN KEY (NRTORIHIKIKANRI) REFERENCES ET200 (NRTORIHIKIKANRI)
);

#セット指示データ管理(L) - セット指示明細(LT011)
CREATE TABLE LT011(
     NRSET CHAR(7) NOT NULL COMMENT 'セット指示№',
     SQKOUSEI SMALLINT NOT NULL COMMENT '構成行',
     NRCHILD CHAR(7) NOT NULL COMMENT '構成品内部商品№',
     QTSHIJI INTEGER COMMENT '予定取引数',
     QTJISSEKI INTEGER COMMENT '実績取引数',
     PRTORIHIKI INTEGER COMMENT '取引単価',
     NRLOCATION CHAR(5) COMMENT 'ロケ№',
     TXLOTNUMBER CHAR(40) COMMENT 'ロット№',
     NRTORIHIKIKANRI CHAR(7) NOT NULL COMMENT '取引管理№',
     AMJISSEKI INTEGER COMMENT '実績取引額',
CONSTRAINT LT011_PK PRIMARY KEY (NRSET, SQKOUSEI),
CONSTRAINT LT011_SK1 UNIQUE (NRTORIHIKIKANRI),
CONSTRAINT LT011_FK1 FOREIGN KEY (NRSET) REFERENCES LT010 (NRSET),
CONSTRAINT LT011_FK2 FOREIGN KEY (NRCHILD) REFERENCES BT020 (NRSYOHIN),
CONSTRAINT LT011_FK3 FOREIGN KEY (NRTORIHIKIKANRI) REFERENCES ET200 (NRTORIHIKIKANRI)
);

#統計データ管理(Y) - 年次取引SUM(YT010)
CREATE TABLE YT010(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     AMURIKISYUZAN BIGINT COMMENT '期首売掛残高',
     AMURISYUK BIGINT COMMENT '期間出荷売上額',
     AMURITYOK INTEGER COMMENT '期間直出荷売上',
     AMURIHENPIN BIGINT COMMENT '期間出荷返品額',
     AMURIZATSUEKI BIGINT COMMENT '期間雑益売上額',
     AMURIZATSUSON BIGINT COMMENT '期間雑損振替額',
     AMURISOUSAI BIGINT COMMENT '期間売上相殺額',
     AMURINEBIKI BIGINT COMMENT '期間営業値引額',
     AMURIHANHURI BIGINT COMMENT '期間販売費振替',
     AMURIJYURYO BIGINT COMMENT '期間売上受領額',
     AMURIGENKA BIGINT COMMENT '期間売上原価',
     AMURITAX BIGINT COMMENT '期間売上消費税',
     AMKAIKISYUZAN BIGINT COMMENT '期首買掛残高',
     AMKAINYUK BIGINT COMMENT '期間入荷仕入額',
     AMKAITYOK BIGINT COMMENT '期間直入荷仕入',
     AMKAIHENPIN BIGINT COMMENT '期間入荷返品額',
     AMKAIZATSUEKI BIGINT COMMENT '期間雑益振替額',
     AMKAIZATSUSON BIGINT COMMENT '期間雑損仕入額',
     AMKAISOUSAI BIGINT COMMENT '期間仕入相殺額',
     AMKAIGENKA BIGINT COMMENT '期間原価振替額',
     AMKAISIHARAI BIGINT COMMENT '期間仕入支払額',
     AMKAITAX BIGINT COMMENT '期間仕入消費税',
     AMZAIKISYUZAN BIGINT COMMENT '期首在庫残高',
     AMZAINYUK BIGINT COMMENT '期間仕入入庫額',
     AMZAINYUKHEN BIGINT COMMENT '期間仕入返品額',
     AMZAISYUK BIGINT COMMENT '期間売上出庫額',
     AMZAISYUKHEN BIGINT COMMENT '期間売上返品額',
     AMZAIIDOU BIGINT COMMENT '期間移動額',
     AMZAIGENMOU BIGINT COMMENT '期間減耗額',
     AMZAIHYOKAZON BIGINT COMMENT '期間評価損額',
     AMZAIHYOKAEKI BIGINT COMMENT '期間評価益額',
     AMZAISIKAKARI BIGINT COMMENT '期間仕掛出庫額',
     AMZAIZATSUSON BIGINT COMMENT '期間雑損額',
     AMZAIZATSUEKI BIGINT COMMENT '期間雑益額',
     AMZAIKANSEI BIGINT COMMENT '期間完成入庫額',
     AMZAIKAKOUHI BIGINT COMMENT '期間加工費繰入',
     AMZAIZOUGEN BIGINT COMMENT '期間棚増減額',
     AMURIARARI BIGINT COMMENT '期間粗利額',
     AMURIMATSUZAN BIGINT COMMENT '期末売掛残高',
     AMKAIMATSUZAN BIGINT COMMENT '期末買掛残高',
     AMZAIKIMATSUZAN BIGINT COMMENT '期末在庫残高',
CONSTRAINT YT010_PK PRIMARY KEY (DTNEND)
);

#統計データ管理(Y) - 月次取引SUM(YT020)
CREATE TABLE YT020(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月序',
     AMURIKISYUZAN INTEGER COMMENT '期首売掛残高',
     AMURISYUK INTEGER COMMENT '期間出荷売上額',
     AMURITYOK INTEGER COMMENT '期間直出荷売上',
     AMURIHENPIN INTEGER COMMENT '期間出荷返品額',
     AMURIZATSUEKI INTEGER COMMENT '期間雑益売上額',
     AMURIZATSUSON INTEGER COMMENT '期間雑損振替額',
     AMURISOUSAI INTEGER COMMENT '期間売上相殺額',
     AMURINEBIKI INTEGER COMMENT '期間営業値引額',
     AMURIHANHURI INTEGER COMMENT '期間販売費振替',
     AMURIJYURYO INTEGER COMMENT '期間売上受領額',
     AMURIGENKA INTEGER COMMENT '期間売上原価',
     AMURITAX INTEGER COMMENT '期間売上消費税',
     AMKAIKISYUZAN INTEGER COMMENT '期首買掛残高',
     AMKAINYUK INTEGER COMMENT '期間入荷仕入額',
     AMKAITYOK INTEGER COMMENT '期間直入荷仕入',
     AMKAIHENPIN INTEGER COMMENT '期間入荷返品額',
     AMKAIZATSUEKI INTEGER COMMENT '期間雑益振替額',
     AMKAIZATSUSON INTEGER COMMENT '期間雑損仕入額',
     AMKAISOUSAI INTEGER COMMENT '期間仕入相殺額',
     AMKAIGENKA INTEGER COMMENT '期間原価振替額',
     AMKAISIHARAI INTEGER COMMENT '期間仕入支払額',
     AMKAITAX INTEGER COMMENT '期間仕入消費税',
     AMZAIKISYUZAN INTEGER COMMENT '期首在庫残高',
     AMZAINYUK INTEGER COMMENT '期間仕入入庫額',
     AMZAINYUKHEN INTEGER COMMENT '期間仕入返品額',
     AMZAISYUK INTEGER COMMENT '期間売上出庫額',
     AMZAISYUKHEN INTEGER COMMENT '期間売上返品額',
     AMZAIIDOU INTEGER COMMENT '期間移動額',
     AMZAIGENMOU INTEGER COMMENT '期間減耗額',
     AMZAIHYOKAZON INTEGER COMMENT '期間評価損額',
     AMZAIHYOKAEKI INTEGER COMMENT '期間評価益額',
     AMZAISIKAKARI INTEGER COMMENT '期間仕掛出庫額',
     AMZAIZATSUSON INTEGER COMMENT '期間雑損額',
     AMZAIZATSUEKI INTEGER COMMENT '期間雑益額',
     AMZAIKANSEI INTEGER COMMENT '期間完成入庫額',
     AMZAIKAKOUHI INTEGER COMMENT '期間加工費繰入',
     AMZAIZOUGEN INTEGER COMMENT '期間棚増減額',
     AMURIARARI INTEGER COMMENT '期間粗利額',
     AMURIMATSUZAN INTEGER COMMENT '期末売掛残高',
     AMKAIMATSUZAN INTEGER COMMENT '期末買掛残高',
     AMZAIKIMATSUZAN INTEGER COMMENT '期末在庫残高',
CONSTRAINT YT020_PK PRIMARY KEY (DTNEND, DTMSEQ),
CONSTRAINT YT020_FK1 FOREIGN KEY (DTNEND) REFERENCES YT010 (DTNEND)
);

#統計データ管理(Y) - 商品別月次取引SUM(YT030)
CREATE TABLE YT030(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月序',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     AMZAIKISYUZAN INTEGER COMMENT '期首在庫残高',
     QTZAIKISYUZAN INTEGER COMMENT '期首在庫残数',
     AMZAINYUK INTEGER COMMENT '期間仕入入庫額',
     QTZAINYUK INTEGER COMMENT '期間仕入入庫数',
     AMZAINYUKHEN INTEGER COMMENT '期間仕入返品額',
     QTZAINYUKHEN INTEGER COMMENT '期間仕入返品数',
     AMZAISYUK INTEGER COMMENT '期間売上出庫額',
     QTZAISYUK INTEGER COMMENT '期間売上出庫数',
     AMZAISYUKHEN INTEGER COMMENT '期間売上返品額',
     QTZAISYUKHEN INTEGER COMMENT '期間売上返品数',
     AMZAIIDOU INTEGER COMMENT '期間移動額',
     QTZAIIDOU INTEGER COMMENT '期間移動数',
     AMZAIGENMOU INTEGER COMMENT '期間減耗額',
     QTZAIGENMOU INTEGER COMMENT '期間減耗数',
     AMZAIHYOKAZON INTEGER COMMENT '期間評価損額',
     AMZAIHYOKAEKI INTEGER COMMENT '期間評価益額',
     AMZAISIKAKARI INTEGER COMMENT '期間仕掛出庫額',
     QTZAISIKAKARI INTEGER COMMENT '期間仕掛出庫数',
     AMZAIZATSUSON INTEGER COMMENT '期間雑損額',
     QTZAIZATSUSON INTEGER COMMENT '期間雑損数',
     AMZAIZATSUEKI INTEGER COMMENT '期間雑益額',
     QTZAIZATSUEKI INTEGER COMMENT '期間雑益数',
     AMZAIKANSEI INTEGER COMMENT '期間完成入庫額',
     QTZAIKANSEI INTEGER COMMENT '期間完成入庫数',
     AMZAIKAKOUHI INTEGER COMMENT '期間加工費繰入',
     AMZAIZOUGEN INTEGER COMMENT '期間棚増減額',
     QTZAIZOUGEN INTEGER COMMENT '期間棚増減数',
     AMZAIARARI INTEGER COMMENT '期間粗利額',
     AMZAIKIMATSUZAN INTEGER COMMENT '期末在庫残高',
     QTZAIKIMATSUZAN INTEGER COMMENT '期末在庫残数',
CONSTRAINT YT030_PK PRIMARY KEY (DTNEND, DTMSEQ, NRSYOHIN),
CONSTRAINT YT030_FK1 FOREIGN KEY (NRSYOHIN) REFERENCES BT020 (NRSYOHIN),
CONSTRAINT YT030_FK2 FOREIGN KEY (DTNEND, DTMSEQ) REFERENCES YT020 (DTNEND, DTMSEQ)
);

#統計データ管理(Y) - 商品倉庫別月次取引SUM(YT031)
CREATE TABLE YT031(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月序',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     NRSOUKO CHAR(5) NOT NULL COMMENT '倉庫№',
     AMZAIKISYUZAN INTEGER COMMENT '期首在庫残高',
     QTZAIKISYUZAN INTEGER COMMENT '期首在庫残数',
     AMZAINYUK INTEGER COMMENT '期間仕入入庫額',
     QTZAINYUK INTEGER COMMENT '期間仕入入庫数',
     AMZAINYUKHEN INTEGER COMMENT '期間仕入返品額',
     QTZAINYUKHEN INTEGER COMMENT '期間仕入返品数',
     AMZAISYUK INTEGER COMMENT '期間売上出庫額',
     QTZAISYUK INTEGER COMMENT '期間売上出庫数',
     AMZAISYUKHEN INTEGER COMMENT '期間売上返品額',
     QTZAISYUKHEN INTEGER COMMENT '期間売上返品数',
     AMZAIIDOU INTEGER COMMENT '期間移動額',
     QTZAIIDOU INTEGER COMMENT '期間移動数',
     AMZAIGENMOU INTEGER COMMENT '期間減耗額',
     QTZAIGENMOU INTEGER COMMENT '期間減耗数',
     AMZAIHYOKAZON INTEGER COMMENT '期間評価損額',
     AMZAIHYOKAEKI INTEGER COMMENT '期間評価益額',
     AMZAISIKAKARI INTEGER COMMENT '期間仕掛出庫額',
     QTZAISIKAKARI INTEGER COMMENT '期間仕掛出庫数',
     AMZAIZATSUSON INTEGER COMMENT '期間雑損額',
     QTZAIZATSUSON INTEGER COMMENT '期間雑損数',
     AMZAIZATSUEKI INTEGER COMMENT '期間雑益額',
     QTZAIZATSUEKI INTEGER COMMENT '期間雑益数',
     AMZAIKANSEI INTEGER COMMENT '期間完成入庫額',
     QTZAIKANSEI INTEGER COMMENT '期間完成入庫数',
     AMZAIKAKOUHI INTEGER COMMENT '期間加工費繰入',
     AMZAIZOUGEN INTEGER COMMENT '期間棚増減額',
     QTZAIZOUGEN INTEGER COMMENT '期間棚増減数',
     AMZAIARARI INTEGER COMMENT '期間粗利額',
     AMZAIKIMATSUZAN INTEGER COMMENT '期末在庫残高',
     QTZAIKIMATSUZAN INTEGER COMMENT '期末在庫残数',
CONSTRAINT YT031_PK PRIMARY KEY (DTNEND, DTMSEQ, NRSYOHIN, NRSOUKO),
CONSTRAINT YT031_FK1 FOREIGN KEY (DTNEND, DTMSEQ, NRSYOHIN) REFERENCES YT030 (DTNEND, DTMSEQ, NRSYOHIN),
CONSTRAINT YT031_FK2 FOREIGN KEY (NRSYOHIN, NRSOUKO) REFERENCES ET010 (NRSYOHIN, NRSOUKO)
);

#統計データ管理(Y) - 仕入先別月次取引SUM(YT040)
CREATE TABLE YT040(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月序',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     AMKAIKISYUZAN INTEGER COMMENT '期首買掛残高',
     AMKAINYUK INTEGER COMMENT '期間入荷仕入額',
     AMKAITYOK INTEGER COMMENT '期間直入荷仕入',
     AMKAIHENPIN INTEGER COMMENT '期間入荷返品額',
     AMKAIZATSUEKI INTEGER COMMENT '期間雑益振替額',
     AMKAIZATSUSON INTEGER COMMENT '期間雑損仕入額',
     AMKAISOUSAI INTEGER COMMENT '期間仕入相殺額',
     AMKAIGENKA INTEGER COMMENT '期間原価振替額',
     AMKAISIHARAI INTEGER COMMENT '期間支払額',
     AMKAITAX INTEGER COMMENT '期間消費税',
     AMKAIMATSUZAN INTEGER COMMENT '期末買掛残高',
CONSTRAINT YT040_PK PRIMARY KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI),
CONSTRAINT YT040_FK1 FOREIGN KEY (DTNEND, DTMSEQ) REFERENCES YT020 (DTNEND, DTMSEQ),
CONSTRAINT YT040_FK2 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES CT010 (NRTORIHIKISAKI)
);

#統計データ管理(Y) - 仕入商品別月次取引SUM(YT041)
CREATE TABLE YT041(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月序',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '仕入先№',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     AMKAINYUK INTEGER COMMENT '期間入荷仕入額',
     QTKAINYUK INTEGER COMMENT '期間入荷仕入数',
     AMKAITYOK INTEGER COMMENT '期間直入荷仕入額',
     QTKAITYOK INTEGER COMMENT '期間直入荷仕入数',
     AMKAIHENPIN INTEGER COMMENT '期間入荷返品額',
     QTKAIHENPIN INTEGER COMMENT '期間入荷返品数',
     AMKAIGENKA INTEGER COMMENT '期間原価振替額',
     AMKAITAX INTEGER COMMENT '期間仕入消費税',
CONSTRAINT YT041_PK PRIMARY KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI, NRSYOHIN),
CONSTRAINT YT041_FK1 FOREIGN KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI) REFERENCES YT040 (DTNEND, DTMSEQ, NRTORIHIKISAKI)
);

#統計データ管理(Y) - 顧客別月次取引SUM(YT050)
CREATE TABLE YT050(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月序',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     AMURIKISYUZAN INTEGER COMMENT '期首売掛残高',
     AMURISYUK INTEGER COMMENT '期間出荷売上額',
     AMURITYOK INTEGER COMMENT '期間直出荷売上',
     AMURIHENPIN INTEGER COMMENT '期間出荷返品額',
     AMURIZATSUEKI INTEGER COMMENT '期間雑益売上額',
     AMURIZATSUSON INTEGER COMMENT '期間雑損振替額',
     AMURISOUSAI INTEGER COMMENT '期間売上相殺額',
     AMURINEBIKI INTEGER COMMENT '期間営業値引額',
     AMURIHANHURI INTEGER COMMENT '期間販売費振替',
     AMURIJYURYO INTEGER COMMENT '期間受領額',
     AMURIGENKA INTEGER COMMENT '期間売上原価',
     AMURITAX INTEGER COMMENT '期間消費税',
     AMURIARARI INTEGER COMMENT '期間粗利額',
     AMURIMATSUZAN INTEGER COMMENT '期末売掛残高',
CONSTRAINT YT050_PK PRIMARY KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI),
CONSTRAINT YT050_FK1 FOREIGN KEY (DTNEND, DTMSEQ) REFERENCES YT020 (DTNEND, DTMSEQ),
CONSTRAINT YT050_FK2 FOREIGN KEY (NRTORIHIKISAKI) REFERENCES DT010 (NRTORIHIKISAKI)
);

#統計データ管理(Y) - 顧客商品別月次取引SUM(YT051)
CREATE TABLE YT051(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月序',
     NRTORIHIKISAKI CHAR(8) NOT NULL COMMENT '顧客№',
     NRSYOHIN CHAR(7) NOT NULL COMMENT '内部商品№',
     AMURISYUK INTEGER COMMENT '期間出荷売上額',
     QTURISYUK INTEGER COMMENT '期間出荷売上数',
     AMURITYOK INTEGER COMMENT '期間直出荷売上額',
     QTURITYOK INTEGER COMMENT '期間直出荷売上数',
     AMURIHENPIN INTEGER COMMENT '期間出荷返品額',
     QTURIHENPIN INTEGER COMMENT '期間出荷返品数',
     AMURINEBIKI INTEGER COMMENT '期間営業値引額',
     AMURIHANHURI INTEGER COMMENT '期間販売費振替',
     AMURIGENKA INTEGER COMMENT '期間売上原価',
     AMURITAX INTEGER COMMENT '期間売上消費税',
     AMURIARARI INTEGER COMMENT '期間粗利額',
CONSTRAINT YT051_PK PRIMARY KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI, NRSYOHIN),
CONSTRAINT YT051_FK1 FOREIGN KEY (DTNEND, DTMSEQ, NRTORIHIKISAKI) REFERENCES YT050 (DTNEND, DTMSEQ, NRTORIHIKISAKI)
);

#統計データ管理(Y) - 営業担当別月次取引SUM(YT060)
CREATE TABLE YT060(
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月序',
     NRTANTOUJYUGYOIN CHAR(5) NOT NULL COMMENT '担当営業№',
     AMURISYUK INTEGER COMMENT '期間出荷売上額',
     AMURITYOK INTEGER COMMENT '期間直出荷売上',
     AMURIHENPIN INTEGER COMMENT '期間出荷返品額',
     AMURIZATSUEKI INTEGER COMMENT '期間雑益売上額',
     AMURIZATSUSON INTEGER COMMENT '期間雑損振替額',
     AMURINEBIKI INTEGER COMMENT '期間営業値引額',
     AMURIHANHURI INTEGER COMMENT '期間販売費振替',
     AMURIGENKA INTEGER COMMENT '期間売上原価',
     AMURITAX INTEGER COMMENT '期間売上消費税',
     AMURIARARI INTEGER COMMENT '期間粗利額',
CONSTRAINT YT060_PK PRIMARY KEY (DTNEND, DTMSEQ, NRTANTOUJYUGYOIN),
CONSTRAINT YT060_FK1 FOREIGN KEY (DTNEND, DTMSEQ) REFERENCES YT020 (DTNEND, DTMSEQ)
);

#システム制御(Z) - システム変数(ZT010)
CREATE TABLE ZT010(
     IDVARIANT CHAR(20) NOT NULL COMMENT '変数ＩＤ',
     TXNAME CHAR(10) NOT NULL COMMENT '変数名',
     TXTYPE CHAR(10) NOT NULL COMMENT '変数値タイプ',
     TXVALUE CHAR(100) NOT NULL COMMENT '変数値',
     TXREMARKS VARCHAR(300) COMMENT '摘要',
CONSTRAINT ZT010_PK PRIMARY KEY (IDVARIANT)
);

#システム制御(Z) - ユーザ(ZT020)
CREATE TABLE ZT020(
     IDUSER CHAR(5) NOT NULL COMMENT 'ユーザＩＤ',
     TXNAME CHAR(30) NOT NULL COMMENT '漢字名',
     TXPASSWORD CHAR(50) NOT NULL COMMENT 'パスワード',
     DTVALID DATE NOT NULL COMMENT '発効日',
     DTEXPIRE DATE COMMENT '失効日',
     TXEMAIL CHAR(40) COMMENT 'メールアドレス',
     TXMENUS CHAR(30) NOT NULL COMMENT '利用可能メニュー',
     NREMPLOYEE CHAR(5) COMMENT '従業員№',
CONSTRAINT ZT020_PK PRIMARY KEY (IDUSER),
CONSTRAINT ZT020_FK1 FOREIGN KEY (NREMPLOYEE) REFERENCES AT020 (NRJYUGYOIN)
);

#システム制御(Z) - 採番テーブル(ZT030)
CREATE TABLE ZT030(
     IDNUMBER CHAR(20) NOT NULL COMMENT '番号ＩＤ',
     TXPREFIX CHAR(4) COMMENT '冒頭文字',
     NRNUMDIGIT SMALLINT NOT NULL COMMENT '数字桁数',
     NRCURRENT INTEGER COMMENT '番号現在値',
     FGWITHCD CHAR(1) NOT NULL COMMENT 'ＣＤ付加フラグ',
CONSTRAINT ZT030_PK PRIMARY KEY (IDNUMBER)
);

#システム制御(Z) - ユーザ定義区分(ZT040)
CREATE TABLE ZT040(
     IDUSERKUBUN CHAR(20) NOT NULL COMMENT 'ユーザ区分ＩＤ',
     KBUSERKUBUN CHAR(2) NOT NULL COMMENT 'ユーザ区分値',
     TXUSERKUBUN CHAR(20) NOT NULL COMMENT '区分値摘要',
     SQLIST SMALLINT NOT NULL COMMENT '一覧順序',
CONSTRAINT ZT040_PK PRIMARY KEY (IDUSERKUBUN, KBUSERKUBUN)
);

#システム制御(Z) - セッション(ZT050)
CREATE TABLE ZT050(
     NRSESSION CHAR(7) NOT NULL COMMENT 'セッション№',
     DTLOGIN DATETIME NOT NULL COMMENT 'ログイン日時',
     DTLOGOUT DATETIME COMMENT 'ログアウト日時',
     IDUSER CHAR(5) NOT NULL COMMENT 'ユーザＩＤ',
     TXIPADDRESS CHAR(20) NOT NULL COMMENT 'IPアドレス',
     VLVERSION CHAR(10) NOT NULL COMMENT '処理系バージョン',
     KBSESSIONSTATUS CHAR(2) COMMENT '終了状態コード',
CONSTRAINT ZT050_PK PRIMARY KEY (NRSESSION),
CONSTRAINT ZT050_FK1 FOREIGN KEY (IDUSER) REFERENCES ZT020 (IDUSER)
);

#システム制御(Z) - セッション明細(ZT051)
CREATE TABLE ZT051(
     NRSESSION CHAR(7) NOT NULL COMMENT 'セッション№',
     SQPROGRAM SMALLINT NOT NULL COMMENT 'PGM行番',
     IDMENU CHAR(2) NOT NULL COMMENT 'メニュー区分',
     IDPROGRAM CHAR(10) NOT NULL COMMENT 'プログラムＩＤ',
     TXPROGRAM CHAR(30) NOT NULL COMMENT '（プログラム名）',
     DTSTART DATETIME NOT NULL COMMENT '利用開始日時',
     DTEND DATETIME COMMENT '利用終了日時',
     KBPROGRAMSTATUS CHAR(2) COMMENT '終了状態コード',
     TXERRORLOG VARCHAR(300) COMMENT 'エラーログ',
CONSTRAINT ZT051_PK PRIMARY KEY (NRSESSION, SQPROGRAM),
CONSTRAINT ZT051_FK1 FOREIGN KEY (NRSESSION) REFERENCES ZT050 (NRSESSION)
);

#システム制御(Z) - 消費税率(ZT060)
CREATE TABLE ZT060(
     DTSTART DATE NOT NULL COMMENT '税率開始日',
     VLTAXRATE NUMERIC(3.2) NOT NULL COMMENT '消費税率',
CONSTRAINT ZT060_PK PRIMARY KEY (DTSTART)
);

#システム制御(Z) - 休日テーブル(ZT070)
CREATE TABLE ZT070(
     KBCALENDAR CHAR(2) NOT NULL COMMENT 'カレンダー区分',
     DTOFF DATE NOT NULL COMMENT '休日日付',
     TXOFF CHAR(20) COMMENT '摘要',
CONSTRAINT ZT070_PK PRIMARY KEY (KBCALENDAR, DTOFF)
);

#システム制御(Z) - 年次為替レート(ZT080)
CREATE TABLE ZT080(
     KBCURRENCY CHAR(3) NOT NULL COMMENT '通貨区分',
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     VLRATEB FLOAT NOT NULL COMMENT 'ＴＴＢレート',
     VLRATEM FLOAT NOT NULL COMMENT 'ＴＴＭレート',
     VLRATES FLOAT NOT NULL COMMENT 'ＴＴＳレート',
CONSTRAINT ZT080_PK PRIMARY KEY (KBCURRENCY, DTNEND)
);

#システム制御(Z) - 月次為替レート(ZT081)
CREATE TABLE ZT081(
     KBCURRENCY CHAR(3) NOT NULL COMMENT '通貨区分',
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月度',
     VLRATEB FLOAT NOT NULL COMMENT 'ＴＴＢレート',
     VLRATEM FLOAT NOT NULL COMMENT 'ＴＴＭレート',
     VLRATES FLOAT NOT NULL COMMENT 'ＴＴＳレート',
CONSTRAINT ZT081_PK PRIMARY KEY (KBCURRENCY, DTNEND, DTMSEQ),
CONSTRAINT ZT081_FK1 FOREIGN KEY (KBCURRENCY, DTNEND) REFERENCES ZT080 (KBCURRENCY, DTNEND)
);

