
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `AT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AT010` (
  `CDBUMON` char(5) NOT NULL,
  `TXBUMON` char(30) NOT NULL,
  `NRKANRISYA` char(5) NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`CDBUMON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `AT011`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AT011` (
  `CDBUMON` char(5) NOT NULL,
  `DTHAKKOUNENGETSU` char(6) NOT NULL,
  `CDJYOUIBUMON` char(5) NOT NULL,
  `DTSIKKOUNENGETSU` char(6) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`CDBUMON`,`DTHAKKOUNENGETSU`),
  KEY `IndexAT011WithCDJYOUIBUMON` (`CDJYOUIBUMON`),
  KEY `IndexAT011WithCDBUMON` (`CDBUMON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `AT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AT020` (
  `NRJYUGYOIN` char(5) NOT NULL,
  `TXKANA` char(20) NOT NULL,
  `TXKANJI` char(20) NOT NULL,
  `KBKOYOU` char(5) NOT NULL,
  `DTNYUSYA` date NOT NULL,
  `DTTAISYA` date DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRJYUGYOIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `AT021`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AT021` (
  `NRJYUGYOIN` char(5) NOT NULL,
  `DTSYOZOKUNENGETSU` char(6) NOT NULL,
  `CDBUMON` char(5) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRJYUGYOIN`,`DTSYOZOKUNENGETSU`),
  KEY `IndexAT021WithNRJYUGYOIN` (`NRJYUGYOIN`),
  KEY `IndexAT021WithCDBUMON` (`CDBUMON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `AT030`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `AT030` (
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `TXKANA` char(40) NOT NULL,
  `TXKANJI` char(40) NOT NULL,
  `KBCOUNTRY` char(3) NOT NULL,
  `KBCURRENCY` char(3) NOT NULL,
  `NRYUBIN` char(8) NOT NULL,
  `TXJYUSYO1` char(30) NOT NULL,
  `TXJYUSYO2` char(30) DEFAULT NULL,
  `NRDENWA` char(14) NOT NULL,
  `NRFAX` char(14) NOT NULL,
  `TXURL` char(40) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTORIHIKISAKI`),
  UNIQUE KEY `AT030_SK1` (`TXKANJI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `BT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `BT010` (
  `CDMAKER` char(5) NOT NULL,
  `TXMAKER` char(40) NOT NULL,
  `TXMAKERABR` char(10) NOT NULL,
  `KBCOUNTRY` char(3) NOT NULL,
  `NRYUBIN` char(8) NOT NULL,
  `TXJYUSYO` char(40) NOT NULL,
  `NRDENWA` char(14) NOT NULL,
  `NRFAX` char(14) NOT NULL,
  `TXURL` char(40) DEFAULT NULL,
  `TXEMAIL` char(40) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`CDMAKER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `BT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `BT020` (
  `NRSYOHIN` char(7) NOT NULL,
  `TXSYOHIN` char(30) NOT NULL,
  `TXHINBAN` char(20) NOT NULL,
  `TXSIYOU` char(50) DEFAULT NULL,
  `TXIMAGEFILENAME` char(30) DEFAULT NULL,
  `KBSYOHIN` char(5) NOT NULL,
  `CDMAKER` char(5) NOT NULL,
  `PRHANBAI` int(11) DEFAULT '0',
  `PRSIIRE` int(11) DEFAULT '0',
  `KBZAIKOUM` char(5) NOT NULL,
  `QTHANBAIUNIT` int(11) NOT NULL DEFAULT '0',
  `QTANZENZAIKO` int(11) DEFAULT '0',
  `QTJYOUGENZAIKO` int(11) NOT NULL DEFAULT '0',
  `FGLOTKANRI` char(1) NOT NULL,
  `FGLISTSYOHIN` char(1) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSYOHIN`),
  UNIQUE KEY `BT020_SK1` (`TXHINBAN`),
  KEY `IndexBT020WithCDMAKER` (`CDMAKER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `BT021`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `BT021` (
  `NRSYOHIN` char(7) NOT NULL,
  `NRCHILD` char(7) NOT NULL,
  `RTKOUSEI` int(11) NOT NULL DEFAULT '0',
  `FGNOUHIN` char(1) NOT NULL,
  `SQLIST` smallint(6) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSYOHIN`,`NRCHILD`),
  KEY `IndexBT021WithNRSYOHIN_SQLIST` (`NRSYOHIN`,`SQLIST`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `BT030`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `BT030` (
  `NRSOUKO` char(5) NOT NULL,
  `TXSOUKO` char(20) NOT NULL,
  `TXSOUKOENG` char(30) DEFAULT NULL,
  `NRYUBIN` char(8) NOT NULL,
  `TXJYUSYO` char(40) NOT NULL,
  `TXJYUSYOENG` char(40) DEFAULT NULL,
  `NRDENWA` char(14) NOT NULL,
  `NRFAX` char(14) NOT NULL,
  `NRDEFAULTLOCATION` char(5) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSOUKO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `BT031`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `BT031` (
  `NRSOUKO` char(5) NOT NULL,
  `NRLOCATION` char(5) NOT NULL,
  `TXTEKIYO` char(20) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSOUKO`,`NRLOCATION`),
  KEY `IndexBT031WithNRSOUKO` (`NRSOUKO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `CT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `CT010` (
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `TXTANTOUBUSYO` char(30) NOT NULL,
  `TXTANTOUSYA` char(40) DEFAULT NULL,
  `TXTANTOUSYASYOKUI` char(10) DEFAULT NULL,
  `TXTANTOUSYAEMAIL` char(40) DEFAULT NULL,
  `TXTANTOUSYADENWA` char(20) DEFAULT NULL,
  `KBSIHARAIHOUHOU` char(2) NOT NULL,
  `TXHURIKOMISAKI` char(50) DEFAULT NULL,
  `VLNYUKINSAITO` smallint(6) NOT NULL DEFAULT '0',
  `NRTANTOUJYUGYOIN` char(5) NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `AMKISYUKAIKAKE` decimal(11,2) DEFAULT '0.00',
  `AMKEIJYOU` decimal(11,2) DEFAULT '0.00',
  `AMSIHARAI` decimal(11,2) DEFAULT '0.00',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTORIHIKISAKI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `CT011`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `CT011` (
  `NRSYOHIN` char(7) NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `DTHAKKOU` date NOT NULL,
  `DTSIKKOU` date NOT NULL,
  `KBSIIREUM` char(5) NOT NULL,
  `QTSIIRETANNI` int(11) NOT NULL DEFAULT '0',
  `VLKANZANKEISU` int(11) NOT NULL DEFAULT '0',
  `PRSIIRETANKA` decimal(10,2) NOT NULL DEFAULT '0.00',
  `VLLEADTIME` smallint(6) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSYOHIN`,`NRTORIHIKISAKI`,`DTHAKKOU`),
  KEY `IndexCT011WithNRTORIHIKISAKI` (`NRTORIHIKISAKI`),
  KEY `IndexCT011WithNRSYOHIN` (`NRSYOHIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `CT100`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `CT100` (
  `NRSIIRE` char(7) NOT NULL,
  `KBAKADEN` char(2) NOT NULL,
  `FGVALID` char(1) NOT NULL,
  `KBSIIRE` char(2) NOT NULL,
  `DTSIIRE` date NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `NRSYOHIN` char(7) DEFAULT NULL,
  `TXSYOHIN` char(30) DEFAULT NULL,
  `PRSIIRE` decimal(10,2) DEFAULT '0.00',
  `KBCURRENCY` char(3) NOT NULL,
  `QTSIIRE` int(11) DEFAULT '0',
  `KBSIIREUM` char(5) NOT NULL,
  `AMSIIRE` decimal(11,2) NOT NULL DEFAULT '0.00',
  `AMTAX` int(11) DEFAULT '0',
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `NRSIHARAIIRAI` char(7) DEFAULT NULL,
  `DTCREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSIIRE`),
  KEY `IndexCT100WithNRTORIHIKISAKI` (`NRTORIHIKISAKI`),
  KEY `IndexCT100WithNRSIHARAIIRAI` (`NRSIHARAIIRAI`),
  KEY `IndexCT100WithNRTORIHIKIKANRI_NRSIIRE` (`NRTORIHIKIKANRI`,`NRSIIRE`),
  KEY `IndexCT100WithDTCREATE` (`DTCREATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `CT110`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `CT110` (
  `NRSIHARAIIRAI` char(7) NOT NULL,
  `DTSIHARAIIRAI` date NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `TXSEIKYUNO` char(20) DEFAULT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `FGSYOUNIN` char(1) NOT NULL,
  `NRSIHARAI` char(7) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `KBSIHARAIHOUHOU` char(2) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSIHARAIIRAI`),
  UNIQUE KEY `CT110_SK1` (`NRTORIHIKIKANRI`),
  KEY `IndexCT110WithNRSIHARAI` (`NRSIHARAI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `CT120`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `CT120` (
  `NRSIHARAI` char(7) NOT NULL,
  `DTSIHARAI` date NOT NULL,
  `KBSIHARAIHOUHOU` char(2) NOT NULL,
  `KBCURRENCY` char(3) NOT NULL,
  `AMNAIKASIHARAI` int(11) DEFAULT '0',
  `AMTESURYO` int(11) DEFAULT '0',
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSIHARAI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `DT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DT010` (
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `CDKAKERITSURANK` char(2) NOT NULL,
  `TXTANTOUBUSYO` char(30) NOT NULL,
  `TXTANTOUSYA` char(40) DEFAULT NULL,
  `TXTANTOUSYASYOKUI` char(10) DEFAULT NULL,
  `TXTANTOUSYAEMAIL` char(40) DEFAULT NULL,
  `TXTANTOUSYADENWA` char(20) DEFAULT NULL,
  `KBSEIKYUHOUSHIKI` char(2) NOT NULL,
  `TXSIMEBI` char(10) DEFAULT NULL,
  `CDNOUHINSYOYOSHIKI` char(4) DEFAULT NULL,
  `KBNYUKINHOUHOU` char(2) NOT NULL,
  `VLNYUKINSAITO` smallint(6) NOT NULL DEFAULT '0',
  `AMYOSHIN` int(11) NOT NULL DEFAULT '0',
  `NRTANTOUJYUGYOIN` char(5) NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `AMKISYUURIKAKE` int(11) DEFAULT '0',
  `AMKEIJYOU` int(11) DEFAULT '0',
  `AMKAISYU` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTORIHIKISAKI`),
  KEY `IndexDT010WithNRTANTOUJYUGYOIN` (`NRTANTOUJYUGYOIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `DT011`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DT011` (
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `SQSYUKKASAKI` smallint(6) NOT NULL DEFAULT '0',
  `TXKANJI` char(40) NOT NULL,
  `NRYUBIN` char(8) NOT NULL,
  `TXJYUSYO` char(40) NOT NULL,
  `NRDENWA` char(14) NOT NULL,
  `NRFAX` char(14) DEFAULT NULL,
  `VLUNSOULT` smallint(6) NOT NULL DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTORIHIKISAKI`,`SQSYUKKASAKI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `DT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DT020` (
  `CDKAKERITSURANK` char(2) NOT NULL,
  `TXKAKERITSURANK` char(20) NOT NULL,
  `VLKAKERITSU` decimal(3,2) NOT NULL DEFAULT '0.00',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`CDKAKERITSURANK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `DT100`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DT100` (
  `NRURIAGE` char(7) NOT NULL,
  `KBAKADEN` char(2) NOT NULL,
  `FGVALID` char(1) NOT NULL,
  `KBURIAGE` char(2) NOT NULL,
  `DTURIAGE` date NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `NRSYOHIN` char(7) DEFAULT NULL,
  `TXSYOHIN` char(30) DEFAULT NULL,
  `PRHANBAI` int(11) DEFAULT '0',
  `PRURIAGE` int(11) DEFAULT '0',
  `QTURIAGE` int(11) DEFAULT '0',
  `KBURIAGEUM` char(5) NOT NULL,
  `AMURIAGE` int(11) DEFAULT '0',
  `AMTAX` int(11) DEFAULT '0',
  `AMGENKA` int(11) DEFAULT '0',
  `NRSEIKYU` char(7) DEFAULT NULL,
  `NRJYUGYOIN` char(5) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `DTCREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRURIAGE`),
  KEY `IndexDT100WithNRTORIHIKISAKI` (`NRTORIHIKISAKI`),
  KEY `IndexDT100WithNRTORIHIKIKANRI_NRURIAGE` (`NRTORIHIKIKANRI`,`NRURIAGE`),
  KEY `IndexDT100WithDTCREATE` (`DTCREATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `DT110`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DT110` (
  `NRSEIKYU` char(7) NOT NULL,
  `DTSEIKYU` date NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `DTHAKKOU` date DEFAULT NULL,
  `DTNYUKIN` date DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSEIKYU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `DT120`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DT120` (
  `NRJYURYOU` char(7) NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `DTJYURYOU` date NOT NULL,
  `KBNYUKINHOUHOU` char(2) NOT NULL,
  `AMJYURYOU` int(11) NOT NULL DEFAULT '0',
  `AMTESURYOU` int(11) DEFAULT '0',
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRJYURYOU`),
  UNIQUE KEY `DT120_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ET010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ET010` (
  `NRSYOHIN` char(7) NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `NRLOCATION` char(5) DEFAULT NULL,
  `QTANZENZAIKO` int(11) DEFAULT '0',
  `QTJYOUGENZAIKO` int(11) DEFAULT '0',
  `QTKISYUZAIKO` int(11) DEFAULT '0',
  `QTNYUKO` int(11) DEFAULT '0',
  `QTSYUKKO` int(11) DEFAULT '0',
  `AMKISYUZAIKO` int(11) DEFAULT '0',
  `AMNYUKO` int(11) DEFAULT '0',
  `AMSYUKKO` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSYOHIN`,`NRSOUKO`),
  KEY `IndexET010WithNRSOUKO` (`NRSOUKO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ET100`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ET100` (
  `NRUKEBARAI` char(7) NOT NULL,
  `KBAKADEN` char(2) NOT NULL,
  `FGVALID` char(1) NOT NULL,
  `KBUKEBARAI` char(2) NOT NULL,
  `DTUKEBARAI` date NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `NRLOCATION` char(5) NOT NULL,
  `NRIDOUSOUKO` char(5) DEFAULT NULL,
  `NRTORIHIKISAKI` char(8) DEFAULT NULL,
  `SQSYUKKASAKI` smallint(6) DEFAULT '0',
  `NRSYOHIN` char(7) NOT NULL,
  `TXLOTNUMBER` char(40) NOT NULL,
  `QTUKEBARAI` int(11) DEFAULT '0',
  `AMUKEBARAI` int(11) DEFAULT '0',
  `AMSAGAKU` int(11) DEFAULT '0',
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `DTCREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRUKEBARAI`),
  KEY `IndexET100WithNRTORIHIKIKANRI_NRUKEBARAI` (`NRTORIHIKIKANRI`,`NRUKEBARAI`),
  KEY `IndexET100WithDTCREATE` (`DTCREATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ET200`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ET200` (
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `KBYOTEI` char(2) NOT NULL,
  `DTYOTEI` date NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `NRIDOUSOUKO` char(5) DEFAULT NULL,
  `NRTORIHIKISAKI` char(8) DEFAULT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `QTYOTEI` int(11) DEFAULT '0',
  `NRSANSYOU` char(15) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTORIHIKIKANRI`),
  KEY `IndexET200WithNRSYOHIN_NRSOUKO` (`NRSYOHIN`,`NRSOUKO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `FT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `FT010` (
  `NRHATTYU` char(7) NOT NULL,
  `DTHATTYU` date NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `NRJYUGYOIN` char(5) NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `FGKAKUNIN` char(1) NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `DTKIBOUNOUKI` date DEFAULT NULL,
  `DTHAKKOU` date DEFAULT NULL,
  `DTTORIKESHI` date DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRHATTYU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `FT011`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `FT011` (
  `NRHATTYU` char(7) NOT NULL,
  `SQHATTYU` smallint(6) NOT NULL DEFAULT '0',
  `NRSYOHIN` char(7) NOT NULL,
  `PRHATTYU` decimal(10,2) NOT NULL DEFAULT '0.00',
  `QTHATTYU` int(11) NOT NULL DEFAULT '0',
  `DTKIBOUNOUKI` date NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRHATTYU`,`SQHATTYU`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `FT012`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `FT012` (
  `NRHATTYU` char(7) NOT NULL,
  `SQHATTYU` smallint(6) NOT NULL DEFAULT '0',
  `SQNYUKA` smallint(6) NOT NULL DEFAULT '0',
  `DTYOTEINYUKA` date NOT NULL,
  `FGKAKUNIN` char(1) NOT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `QTYOTEISIIRE` int(11) NOT NULL DEFAULT '0',
  `QTJITSUSIIRE` int(11) DEFAULT '0',
  `QTDEFECT` int(11) DEFAULT '0',
  `PRSIIRE` decimal(10,2) NOT NULL DEFAULT '0.00',
  `TXLOTNUMBER` char(40) DEFAULT NULL,
  `NRLOCATION` char(5) DEFAULT NULL,
  `NRNYUKA` char(7) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRHATTYU`,`SQHATTYU`,`SQNYUKA`),
  UNIQUE KEY `FT012_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `FT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `FT020` (
  `NRNYUKA` char(7) NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `DTNYUKA` date NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRNYUKA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `GT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `GT010` (
  `NRJYUTYU` char(7) NOT NULL,
  `DTJYUTYU` date NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `SQSYUKKASAKI` smallint(6) NOT NULL DEFAULT '0',
  `TXTYUBAN` char(15) DEFAULT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `DTTORIKESHI` date DEFAULT NULL,
  `NRMITSUMORI` char(7) DEFAULT NULL,
  `SQVERSION` smallint(6) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRJYUTYU`),
  KEY `IndexGT010WithNRMITSUMORI_SQVERSION` (`NRMITSUMORI`,`SQVERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `GT011`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `GT011` (
  `NRJYUTYU` char(7) NOT NULL,
  `SQJYUTYU` smallint(6) NOT NULL DEFAULT '0',
  `NRSYOHIN` char(7) NOT NULL,
  `PRJYUTYU` int(11) NOT NULL DEFAULT '0',
  `QTJYUTYU` int(11) NOT NULL DEFAULT '0',
  `DTKIBOUNOUKI` date NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRJYUTYU`,`SQJYUTYU`),
  KEY `IndexGT011WithNRTORIHIKISAKI` (`NRTORIHIKISAKI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `GT012`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `GT012` (
  `NRJYUTYU` char(7) NOT NULL,
  `SQJYUTYU` smallint(6) NOT NULL DEFAULT '0',
  `SQSYUKKA` smallint(6) NOT NULL DEFAULT '0',
  `NRSOUKO` char(5) NOT NULL,
  `DTYOTEISYUKKA` date NOT NULL,
  `QTYOTEISYUKKA` int(11) NOT NULL DEFAULT '0',
  `QTJITSUSYUKKA` int(11) DEFAULT '0',
  `QTTORIKESHI` int(11) DEFAULT '0',
  `PRSYUKKO` int(11) DEFAULT '0',
  `TXLOTNUMBER` char(40) DEFAULT NULL,
  `NRSYUKKA` char(7) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRJYUTYU`,`SQJYUTYU`,`SQSYUKKA`),
  UNIQUE KEY `GT012_SK1` (`NRTORIHIKIKANRI`),
  KEY `IndexGT012WithNRSYUKKA` (`NRSYUKKA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `GT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `GT020` (
  `NRSYUKKA` char(7) NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `SQSYUKKASAKI` smallint(6) NOT NULL DEFAULT '0',
  `NRSOUKO` char(5) NOT NULL,
  `DTSYUKKA` date NOT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRSEIKYU` char(7) DEFAULT NULL,
  `TMHAKKOU` datetime DEFAULT NULL,
  `TMKANRYO` datetime DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSYUKKA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `GT030`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `GT030` (
  `NRMITSUMORI` char(7) NOT NULL,
  `SQVERSION` smallint(6) NOT NULL DEFAULT '0',
  `DTMITSUMORI` date NOT NULL,
  `NRTORIHIKISAKI` char(8) DEFAULT NULL,
  `SQSYUKKASAKI` smallint(6) DEFAULT '0',
  `TXKOKYAKUMEI` char(40) DEFAULT NULL,
  `TXTYUBAN` char(15) DEFAULT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRMITSUMORI`,`SQVERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `GT031`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `GT031` (
  `NRMITSUMORI` char(7) NOT NULL,
  `SQVERSION` smallint(6) NOT NULL DEFAULT '0',
  `SQMITSUMORI` smallint(6) NOT NULL DEFAULT '0',
  `NRSYOHIN` char(7) NOT NULL,
  `PRJYUTYU` int(11) NOT NULL DEFAULT '0',
  `QTJYUTYU` int(11) NOT NULL DEFAULT '0',
  `DTKIBOUNOUKI` date NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRMITSUMORI`,`SQVERSION`,`SQMITSUMORI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `HT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `HT010` (
  `NRSIIREHURIKAE` char(7) NOT NULL,
  `KBSIIREHURIKAE` char(2) NOT NULL,
  `DTTORIHIKI` date NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `AMTORIHIKI` decimal(10,2) NOT NULL DEFAULT '0.00',
  `TXTEKIYO` char(30) NOT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSIIREHURIKAE`),
  UNIQUE KEY `HT010_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `HT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `HT020` (
  `NRTOKUSYUSIIRE` char(7) NOT NULL,
  `KBTOKUSYUSIIRE` char(2) NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `DTTORIHIKI` date NOT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `NRLOCATION` char(5) NOT NULL,
  `TXLOTNUMBER` char(40) DEFAULT NULL,
  `PRTORIHIKI` decimal(10,2) NOT NULL DEFAULT '0.00',
  `QTTORIHIKI` int(11) NOT NULL DEFAULT '0',
  `KBTORIHIKIUM` char(5) NOT NULL,
  `PRUKEBARAI` int(11) DEFAULT '0',
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTOKUSYUSIIRE`),
  UNIQUE KEY `HT020_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `JT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `JT010` (
  `NRURIAGEHURIKAE` char(7) NOT NULL,
  `KBURIAGEHURIKAE` char(2) NOT NULL,
  `DTTORIHIKI` date NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `AMTORIHIKI` int(11) NOT NULL DEFAULT '0',
  `TXTEKIYO` char(30) NOT NULL,
  `NRSEIKYU` char(7) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRURIAGEHURIKAE`),
  UNIQUE KEY `JT010_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `JT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `JT020` (
  `NRTOKUSYUURIAGE` char(7) NOT NULL,
  `KBTOKUSYUURIAGE` char(2) NOT NULL,
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `SQSYUKKASAKI` smallint(6) NOT NULL DEFAULT '0',
  `DTTORIHIKI` date NOT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `TXLOTNUMBER` char(40) DEFAULT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `NRLOCATION` char(5) NOT NULL,
  `PRTORIHIKI` int(11) NOT NULL DEFAULT '0',
  `QTTORIHIKI` int(11) NOT NULL DEFAULT '0',
  `PRUKEBARAI` int(11) DEFAULT '0',
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRSEIKYU` char(7) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTOKUSYUURIAGE`),
  UNIQUE KEY `JT020_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `KT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `KT010` (
  `NRTANAOROSHI` char(7) NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `NRLOCATION` char(5) DEFAULT NULL,
  `DTKIJYUN` datetime DEFAULT NULL,
  `DTKOUSHIN` datetime DEFAULT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTANAOROSHI`),
  UNIQUE KEY `KT010_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `KT011`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `KT011` (
  `NRTANAOROSHI` char(7) NOT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `NRLOCATION` char(5) NOT NULL,
  `PRUKEBARAI` int(11) NOT NULL DEFAULT '0',
  `QTTYOUBO` int(11) DEFAULT '0',
  `QTJITSUTANA` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRTANAOROSHI`,`NRSYOHIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `KT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `KT020` (
  `NRZAIKOIDOU` char(7) NOT NULL,
  `DTSHIJI` date NOT NULL,
  `NRSOUKOFROM` char(5) NOT NULL,
  `NRSOUKOTO` char(5) NOT NULL,
  `DTKANRYOYOTEI` date NOT NULL,
  `TMHAKKOU` datetime DEFAULT NULL,
  `TMKANRYO` datetime DEFAULT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRZAIKOIDOU`),
  UNIQUE KEY `KT020_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `KT021`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `KT021` (
  `NRZAIKOIDOU` char(7) NOT NULL,
  `SQZAIKOIDOU` smallint(6) NOT NULL DEFAULT '0',
  `NRLOCATIONTO` char(5) DEFAULT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `TXLOTNUMBER` char(40) DEFAULT NULL,
  `QTIDOU` int(11) NOT NULL DEFAULT '0',
  `PRIDOU` int(11) DEFAULT '0',
  `NRTORIHIKIKANRIFROM` char(7) NOT NULL,
  `NRTORIHIKIKANRITO` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRZAIKOIDOU`,`SQZAIKOIDOU`),
  UNIQUE KEY `KT021_SK1` (`NRTORIHIKIKANRIFROM`),
  UNIQUE KEY `KT021_SK2` (`NRTORIHIKIKANRITO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `KT030`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `KT030` (
  `NRZAIKOHURIKAE` char(7) NOT NULL,
  `KBZAIKOHURIKAE` char(2) NOT NULL,
  `DTHURIKAE` date NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `NRLOCATION` char(5) DEFAULT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `TXLOTNUMBER` char(40) DEFAULT NULL,
  `QTHURIKAE` int(11) DEFAULT '0',
  `AMHURIKAE` int(11) DEFAULT '0',
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRZAIKOHURIKAE`),
  UNIQUE KEY `KT030_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `LT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `LT010` (
  `NRSET` char(7) NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `DTYOTEI` date NOT NULL,
  `TMHAKKOU` datetime DEFAULT NULL,
  `TMJISSEKI` datetime DEFAULT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `QTSHIJI` int(11) NOT NULL DEFAULT '0',
  `QTJISSEKI` int(11) DEFAULT '0',
  `AMJISSEKI` int(11) DEFAULT '0',
  `NRLOCATION` char(5) DEFAULT NULL,
  `TXLOTNUMBER` char(40) DEFAULT NULL,
  `TXTEKIYO` varchar(300) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSET`),
  UNIQUE KEY `LT010_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `LT011`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `LT011` (
  `NRSET` char(7) NOT NULL,
  `SQKOUSEI` smallint(6) NOT NULL DEFAULT '0',
  `NRCHILD` char(7) NOT NULL,
  `QTSHIJI` int(11) DEFAULT '0',
  `QTJISSEKI` int(11) DEFAULT '0',
  `PRTORIHIKI` int(11) DEFAULT '0',
  `NRLOCATION` char(5) DEFAULT NULL,
  `TXLOTNUMBER` char(40) DEFAULT NULL,
  `NRTORIHIKIKANRI` char(7) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSET`,`SQKOUSEI`),
  UNIQUE KEY `LT011_SK1` (`NRTORIHIKIKANRI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT010` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `AMURIKISYUZAN` bigint(20) DEFAULT '0',
  `AMURISYUK` bigint(20) DEFAULT '0',
  `AMURITYOK` bigint(20) DEFAULT '0',
  `AMURIHENPIN` bigint(20) DEFAULT '0',
  `AMURIZATSUEKI` bigint(20) DEFAULT '0',
  `AMURIZATSUSON` bigint(20) DEFAULT '0',
  `AMURISOUSAI` bigint(20) DEFAULT '0',
  `AMURINEBIKI` bigint(20) DEFAULT '0',
  `AMURIHANHURI` bigint(20) DEFAULT '0',
  `AMURIJYURYO` bigint(20) DEFAULT '0',
  `AMURIGENKA` bigint(20) DEFAULT '0',
  `AMURITAX` bigint(20) DEFAULT '0',
  `AMKAIKISYUZAN` bigint(20) DEFAULT '0',
  `AMKAINYUK` bigint(20) DEFAULT '0',
  `AMKAITYOK` bigint(20) DEFAULT '0',
  `AMKAIHENPIN` bigint(20) DEFAULT '0',
  `AMKAIZATSUEKI` bigint(20) DEFAULT '0',
  `AMKAIZATSUSON` bigint(20) DEFAULT '0',
  `AMKAISOUSAI` bigint(20) DEFAULT '0',
  `AMKAIGENKA` bigint(20) DEFAULT '0',
  `AMKAISIHARAI` bigint(20) DEFAULT '0',
  `AMKAITAX` bigint(20) DEFAULT '0',
  `AMZAIKISYUZAN` bigint(20) DEFAULT '0',
  `AMZAINYUK` bigint(20) DEFAULT '0',
  `AMZAINYUKHEN` bigint(20) DEFAULT '0',
  `AMZAISYUK` bigint(20) DEFAULT '0',
  `AMZAISYUKHEN` bigint(20) DEFAULT '0',
  `AMZAIIDOU` bigint(20) DEFAULT '0',
  `AMZAIGENMOU` bigint(20) DEFAULT '0',
  `AMZAIHYOKAZON` bigint(20) DEFAULT '0',
  `AMZAIHYOKAEKI` bigint(20) DEFAULT '0',
  `AMZAISIKAKARI` bigint(20) DEFAULT '0',
  `AMZAIZATSUSON` bigint(20) DEFAULT '0',
  `AMZAIZATSUEKI` bigint(20) DEFAULT '0',
  `AMZAIKANSEI` bigint(20) DEFAULT '0',
  `AMZAIKAKOUHI` bigint(20) DEFAULT '0',
  `AMZAIZOUGEN` bigint(20) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT020` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `AMURIKISYUZAN` int(11) DEFAULT '0',
  `AMURISYUK` int(11) DEFAULT '0',
  `AMURITYOK` int(11) DEFAULT '0',
  `AMURIHENPIN` int(11) DEFAULT '0',
  `AMURIZATSUEKI` int(11) DEFAULT '0',
  `AMURIZATSUSON` int(11) DEFAULT '0',
  `AMURISOUSAI` int(11) DEFAULT '0',
  `AMURINEBIKI` int(11) DEFAULT '0',
  `AMURIHANHURI` int(11) DEFAULT '0',
  `AMURIJYURYO` int(11) DEFAULT '0',
  `AMURIGENKA` int(11) DEFAULT '0',
  `AMURITAX` int(11) DEFAULT '0',
  `AMKAIKISYUZAN` int(11) DEFAULT '0',
  `AMKAINYUK` int(11) DEFAULT '0',
  `AMKAITYOK` int(11) DEFAULT '0',
  `AMKAIHENPIN` int(11) DEFAULT '0',
  `AMKAIZATSUEKI` int(11) DEFAULT '0',
  `AMKAIZATSUSON` int(11) DEFAULT '0',
  `AMKAISOUSAI` int(11) DEFAULT '0',
  `AMKAIGENKA` int(11) DEFAULT '0',
  `AMKAISIHARAI` int(11) DEFAULT '0',
  `AMKAITAX` int(11) DEFAULT '0',
  `AMZAIKISYUZAN` int(11) DEFAULT '0',
  `AMZAINYUK` int(11) DEFAULT '0',
  `AMZAINYUKHEN` int(11) DEFAULT '0',
  `AMZAISYUK` int(11) DEFAULT '0',
  `AMZAISYUKHEN` int(11) DEFAULT '0',
  `AMZAIIDOU` int(11) DEFAULT '0',
  `AMZAIGENMOU` int(11) DEFAULT '0',
  `AMZAIHYOKAZON` int(11) DEFAULT '0',
  `AMZAIHYOKAEKI` int(11) DEFAULT '0',
  `AMZAISIKAKARI` int(11) DEFAULT '0',
  `AMZAIZATSUSON` int(11) DEFAULT '0',
  `AMZAIZATSUEKI` int(11) DEFAULT '0',
  `AMZAIKANSEI` int(11) DEFAULT '0',
  `AMZAIKAKOUHI` int(11) DEFAULT '0',
  `AMZAIZOUGEN` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`,`DTMSEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT030`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT030` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `NRSYOHIN` char(7) NOT NULL,
  `AMZAIKISYUZAN` int(11) DEFAULT '0',
  `QTZAIKISYUZAN` int(11) DEFAULT '0',
  `AMZAINYUK` int(11) DEFAULT '0',
  `QTZAINYUK` int(11) DEFAULT '0',
  `AMZAINYUKHEN` int(11) DEFAULT '0',
  `QTZAINYUKHEN` int(11) DEFAULT '0',
  `AMZAISYUK` int(11) DEFAULT '0',
  `QTZAISYUK` int(11) DEFAULT '0',
  `AMZAISYUKHEN` int(11) DEFAULT '0',
  `QTZAISYUKHEN` int(11) DEFAULT '0',
  `AMZAIIDOU` int(11) DEFAULT '0',
  `QTZAIIDOU` int(11) DEFAULT '0',
  `AMZAIGENMOU` int(11) DEFAULT '0',
  `QTZAIGENMOU` int(11) DEFAULT '0',
  `AMZAIHYOKAZON` int(11) DEFAULT '0',
  `AMZAIHYOKAEKI` int(11) DEFAULT '0',
  `AMZAISIKAKARI` int(11) DEFAULT '0',
  `QTZAISIKAKARI` int(11) DEFAULT '0',
  `AMZAIZATSUSON` int(11) DEFAULT '0',
  `QTZAIZATSUSON` int(11) DEFAULT '0',
  `AMZAIZATSUEKI` int(11) DEFAULT '0',
  `QTZAIZATSUEKI` int(11) DEFAULT '0',
  `AMZAIKANSEI` int(11) DEFAULT '0',
  `QTZAIKANSEI` int(11) DEFAULT '0',
  `AMZAIKAKOUHI` int(11) DEFAULT '0',
  `AMZAIZOUGEN` int(11) DEFAULT '0',
  `QTZAIZOUGEN` int(11) DEFAULT '0',
  `AMZAIARARI` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`,`DTMSEQ`,`NRSYOHIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT031`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT031` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `NRSYOHIN` char(7) NOT NULL,
  `NRSOUKO` char(5) NOT NULL,
  `AMZAIKISYUZAN` int(11) DEFAULT '0',
  `QTZAIKISYUZAN` int(11) DEFAULT '0',
  `AMZAINYUK` int(11) DEFAULT '0',
  `QTZAINYUK` int(11) DEFAULT '0',
  `AMZAINYUKHEN` int(11) DEFAULT '0',
  `QTZAINYUKHEN` int(11) DEFAULT '0',
  `AMZAISYUK` int(11) DEFAULT '0',
  `QTZAISYUK` int(11) DEFAULT '0',
  `AMZAISYUKHEN` int(11) DEFAULT '0',
  `QTZAISYUKHEN` int(11) DEFAULT '0',
  `AMZAIIDOU` int(11) DEFAULT '0',
  `QTZAIIDOU` int(11) DEFAULT '0',
  `AMZAIGENMOU` int(11) DEFAULT '0',
  `QTZAIGENMOU` int(11) DEFAULT '0',
  `AMZAIHYOKAZON` int(11) DEFAULT '0',
  `AMZAIHYOKAEKI` int(11) DEFAULT '0',
  `AMZAISIKAKARI` int(11) DEFAULT '0',
  `QTZAISIKAKARI` int(11) DEFAULT '0',
  `AMZAIZATSUSON` int(11) DEFAULT '0',
  `QTZAIZATSUSON` int(11) DEFAULT '0',
  `AMZAIZATSUEKI` int(11) DEFAULT '0',
  `QTZAIZATSUEKI` int(11) DEFAULT '0',
  `AMZAIKANSEI` int(11) DEFAULT '0',
  `QTZAIKANSEI` int(11) DEFAULT '0',
  `AMZAIKAKOUHI` int(11) DEFAULT '0',
  `AMZAIZOUGEN` int(11) DEFAULT '0',
  `QTZAIZOUGEN` int(11) DEFAULT '0',
  `AMZAIARARI` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`,`DTMSEQ`,`NRSYOHIN`,`NRSOUKO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT040`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT040` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `AMKAIKISYUZAN` int(11) DEFAULT '0',
  `AMKAINYUK` int(11) DEFAULT '0',
  `AMKAITYOK` int(11) DEFAULT '0',
  `AMKAIHENPIN` int(11) DEFAULT '0',
  `AMKAIZATSUEKI` int(11) DEFAULT '0',
  `AMKAIZATSUSON` int(11) DEFAULT '0',
  `AMKAISOUSAI` int(11) DEFAULT '0',
  `AMKAIGENKA` int(11) DEFAULT '0',
  `AMKAISIHARAI` int(11) DEFAULT '0',
  `AMKAITAX` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`,`DTMSEQ`,`NRTORIHIKISAKI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT041`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT041` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `AMKAINYUK` int(11) DEFAULT '0',
  `QTKAINYUK` int(11) DEFAULT '0',
  `AMKAITYOK` int(11) DEFAULT '0',
  `QTKAITYOK` int(11) DEFAULT '0',
  `AMKAIHENPIN` int(11) DEFAULT '0',
  `QTKAIHENPIN` int(11) DEFAULT '0',
  `AMKAIGENKA` int(11) DEFAULT '0',
  `AMKAITAX` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`,`DTMSEQ`,`NRTORIHIKISAKI`,`NRSYOHIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT050`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT050` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `AMURIKISYUZAN` int(11) DEFAULT '0',
  `AMURISYUK` int(11) DEFAULT '0',
  `AMURITYOK` int(11) DEFAULT '0',
  `AMURIHENPIN` int(11) DEFAULT '0',
  `AMURIZATSUEKI` int(11) DEFAULT '0',
  `AMURIZATSUSON` int(11) DEFAULT '0',
  `AMURISOUSAI` int(11) DEFAULT '0',
  `AMURINEBIKI` int(11) DEFAULT '0',
  `AMURIHANHURI` int(11) DEFAULT '0',
  `AMURIJYURYO` int(11) DEFAULT '0',
  `AMURIGENKA` int(11) DEFAULT '0',
  `AMURITAX` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`,`DTMSEQ`,`NRTORIHIKISAKI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT051`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT051` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `NRTORIHIKISAKI` char(8) NOT NULL,
  `NRSYOHIN` char(7) NOT NULL,
  `AMURISYUK` int(11) DEFAULT '0',
  `QTURISYUK` int(11) DEFAULT '0',
  `AMURITYOK` int(11) DEFAULT '0',
  `QTURITYOK` int(11) DEFAULT '0',
  `AMURIHENPIN` int(11) DEFAULT '0',
  `QTURIHENPIN` int(11) DEFAULT '0',
  `AMURINEBIKI` int(11) DEFAULT '0',
  `AMURIHANHURI` int(11) DEFAULT '0',
  `AMURIGENKA` int(11) DEFAULT '0',
  `AMURITAX` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`,`DTMSEQ`,`NRTORIHIKISAKI`,`NRSYOHIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `YT060`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `YT060` (
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `NRTANTOUJYUGYOIN` char(5) NOT NULL,
  `AMURISYUK` int(11) DEFAULT '0',
  `AMURITYOK` int(11) DEFAULT '0',
  `AMURIHENPIN` int(11) DEFAULT '0',
  `AMURIZATSUEKI` int(11) DEFAULT '0',
  `AMURIZATSUSON` int(11) DEFAULT '0',
  `AMURINEBIKI` int(11) DEFAULT '0',
  `AMURIHANHURI` int(11) DEFAULT '0',
  `AMURIGENKA` int(11) DEFAULT '0',
  `AMURITAX` int(11) DEFAULT '0',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTNEND`,`DTMSEQ`,`NRTANTOUJYUGYOIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT010`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT010` (
  `IDVARIANT` char(20) NOT NULL,
  `TXNAME` char(10) NOT NULL,
  `TXTYPE` char(10) NOT NULL,
  `TXVALUE` char(100) NOT NULL,
  `TXREMARKS` varchar(500) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`IDVARIANT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT020`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT020` (
  `IDUSER` char(5) NOT NULL,
  `TXNAME` char(30) NOT NULL,
  `TXPASSWORD` char(50) NOT NULL,
  `DTVALID` date NOT NULL,
  `DTEXPIRE` date NOT NULL,
  `TXEMAIL` char(40) DEFAULT NULL,
  `TXMENUS` char(30) NOT NULL,
  `NREMPLOYEE` char(5) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`IDUSER`),
  KEY `IndexZT020WithNREMPLOYEE` (`NREMPLOYEE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT021`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT021` (
  `IDUSER` char(5) NOT NULL,
  `IDFUNCTION` char(20) NOT NULL,
  `IDFILTER` char(40) NOT NULL,
  `TXVALUE` char(50) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`IDUSER`,`IDFUNCTION`,`IDFILTER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT030`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT030` (
  `IDNUMBER` char(20) NOT NULL,
  `TXPREFIX` char(4) DEFAULT NULL,
  `NRNUMDIGIT` smallint(6) NOT NULL DEFAULT '0',
  `NRCURRENT` int(11) NOT NULL DEFAULT '0',
  `FGWITHCD` char(1) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`IDNUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT040`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT040` (
  `IDUSERKUBUN` char(20) NOT NULL,
  `KBUSERKUBUN` char(5) NOT NULL,
  `TXUSERKUBUN` char(20) NOT NULL,
  `SQLIST` char(2) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`IDUSERKUBUN`,`KBUSERKUBUN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT050`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT050` (
  `NRSESSION` char(7) NOT NULL,
  `DTLOGIN` datetime NOT NULL,
  `DTLOGOUT` datetime DEFAULT NULL,
  `IDUSER` char(5) NOT NULL,
  `TXIPADDRESS` char(20) NOT NULL,
  `VLVERSION` char(10) NOT NULL,
  `KBSESSIONSTATUS` char(3) NOT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSESSION`),
  KEY `IndexZT050WithIDUSER` (`IDUSER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT051`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT051` (
  `NRSESSION` char(7) NOT NULL,
  `SQPROGRAM` smallint(6) NOT NULL DEFAULT '0',
  `IDMENU` char(2) NOT NULL,
  `IDPROGRAM` char(10) NOT NULL,
  `TXPROGRAM` char(30) NOT NULL,
  `DTSTART` datetime NOT NULL,
  `DTEND` datetime DEFAULT NULL,
  `KBPROGRAMSTATUS` char(2) DEFAULT NULL,
  `TXERRORLOG` longtext,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`NRSESSION`,`SQPROGRAM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT060`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT060` (
  `DTSTART` date NOT NULL,
  `VLTAXRATE` decimal(3,2) NOT NULL DEFAULT '0.00',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`DTSTART`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT070`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT070` (
  `KBCALENDAR` char(2) NOT NULL,
  `DTOFF` date NOT NULL,
  `TXOFF` char(20) DEFAULT NULL,
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`KBCALENDAR`,`DTOFF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT080`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT080` (
  `KBCURRENCY` char(3) NOT NULL,
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `VLRATEB` decimal(10,3) NOT NULL DEFAULT '0.000',
  `VLRATEM` decimal(10,3) NOT NULL DEFAULT '0.000',
  `VLRATES` decimal(10,3) NOT NULL DEFAULT '0.000',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`KBCURRENCY`,`DTNEND`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `ZT081`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ZT081` (
  `KBCURRENCY` char(3) NOT NULL,
  `DTNEND` smallint(6) NOT NULL DEFAULT '0',
  `DTMSEQ` smallint(6) NOT NULL DEFAULT '0',
  `VLRATEB` decimal(10,3) NOT NULL DEFAULT '0.000',
  `VLRATEM` decimal(10,3) NOT NULL DEFAULT '0.000',
  `VLRATES` decimal(10,3) NOT NULL DEFAULT '0.000',
  `UPDCOUNTER` int(11) DEFAULT '0',
  PRIMARY KEY (`KBCURRENCY`,`DTNEND`,`DTMSEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

